import {Header,Footer} from '@/components/site-chrome';
import {MonthlyMix} from '@/components/monthly-mix';
import {AnalysisExamples} from '@/components/analysis-examples';
import {AnalysisControls} from '@/components/analysis-controls';
import {DeferredMap} from '@/components/deferred-map';
import {AnalysisArticleList} from '@/components/analysis-article-list';
import {analysisControlsData,mapPlaces,analysisListQuery} from '@/shared/analysis-payload.mjs';
import {getAnalytics,InvalidAnalysis} from '@/server/repositories/analytics';
import {labelName,LABELS} from '@/shared/labels.mjs';
import {regionName} from '@/shared/regions';
import {validRegion} from '@/shared/regions';
import {formatDate} from '@/shared/types';
export const dynamic='force-dynamic';
export const metadata={title:'Themenanalyse · vor Ort',description:'Themenanteile, monatliche Entwicklung und ähnliche Vorgänge in anderen Städten und Kreisen.'};
function Trend({months,color}:{months:any[];color:string}){const width=640,height=230,x=(i:number)=>60+i*540/Math.max(1,months.length-1),y=(n:number)=>190-n*1.5;return <svg className="trend-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Monatlicher Anteil des gewählten Hauptlabels in Prozent. Werte auch in der nachfolgenden Tabelle.">{[0,25,50,75,100].map(n=><g key={n}><line x1={52} x2={618} y1={y(n)} y2={y(n)} stroke="#ddd"/><text x={42} y={y(n)+4} textAnchor="end">{n}%</text></g>)}{months.map((m,i)=><g key={m.month}>{i>0&&m.share!==null&&months[i-1].share!==null&&<line x1={x(i-1)} y1={y(months[i-1].share)} x2={x(i)} y2={y(m.share)} stroke={color} strokeWidth="3"/>}{m.share!==null&&<circle cx={x(i)} cy={y(m.share)} r="5" fill={color}><title>{m.month+': '+m.share.toFixed(1)+' %, '+m.count+' von '+m.total+' Vorgängen'+(m.partial?' (Teilstand)':'')}</title></circle>}{(i%Math.max(1,Math.ceil(months.length/6))===0||i===months.length-1)&&<text x={x(i)} y="218" textAnchor="middle">{m.month.slice(5)}.{m.month.slice(2,4)}</text>}</g>)}</svg>}
export default async function Analysis({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const p=await searchParams;const params=new URLSearchParams(Object.entries(p).filter(([,v])=>typeof v==='string') as [string,string][]);const contextRegion=validRegion(params.get('region')||'')?params.get('region')!:'billerbeck';let d;try{d=await getAnalytics(params);}catch(e){return <div className="screen screen--tabbar"><Header place="Analysen" region={contextRegion}/><main id="inhalt" className="analysis-main"><h1>Auswahl prüfen</h1><p>{e instanceof InvalidAnalysis?e.message:'Die Auswertung konnte nicht geladen werden.'}</p><a href={'/analysen?region='+(validRegion(params.get('region')||'')?params.get('region'):'billerbeck')}>Zeitraum und Filter zurücksetzen</a></main><Footer active="analysen" region={contextRegion}/></div>}
 const color=LABELS.find(l=>l.id===d.label)?.color||'#2352ad';const fmt=(v:number|null)=>v===null?'—':v.toLocaleString('de-DE',{maximumFractionDigits:1})+' %';
 return <div className="screen screen--tabbar analysis-screen"><Header place="Analysen" region={d.region}/><main id="inhalt" className="analysis-main"><div className="analysis-heading"><p className="eyebrow">THEMEN VERSTEHEN</p><h1>Themenanalyse</h1><p>Themenanteile, Entwicklung und der Blick in andere Orte.</p><p className="page-note">Gespeicherte Ergebnisse. Das Öffnen und Filtern dieser Seite startet keine Artikelanalyse.</p></div><AnalysisControls key={params.toString()} data={analysisControlsData(d)} example={params.get('example')||''}/>{!d.storageAvailable&&<p role="status" className="analysis-notice">Datenbank nicht erreichbar. Die Auswertung nutzt den gespeicherten Ersatzstand.</p>}<div id="auswertung" tabIndex={-1} className="analysis-context"><strong>{regionName(d.region)}</strong><span>{formatDate(d.from)} bis {formatDate(d.to)}</span><span>{d.total} unterschiedliche Vorgänge</span></div><details className="analysis-counting"><summary>Was wird gezählt?</summary><p>Gezählt werden Vorgänge auf öffentlichen Tagesordnungen. Das belegt noch keine tatsächliche Beratung. Mehrere Termine derselben zugeordneten Vorgangs-ID zählen im Zeitraum einmal. Bei nicht auflösbaren Vorlagenverknüpfungen können Beratungen derselben Vorlage noch getrennt erfasst sein.</p></details>{(!d.coverage?.complete||!d.coverage?.from||!d.coverage?.to||d.coverage.from>d.from||d.coverage.to<d.to)&&<p className="analysis-notice">Die Quellen decken den Zeitraum nur teilweise ab. Letzter Quellenstand: {d.coverage?formatDate(d.coverage.importedAt):'nicht verfügbar'}. <a href={'/quellen?region='+d.region}>Datenlage ansehen</a></p>}
 <p className="analysis-notice">{d.pendingLabels} Vorgänge in dieser Auswahl warten auf eine Labelanalyse. Sie bleiben unter „Noch nicht eingeordnet“ enthalten. Neue Analysen startet ausschließlich der Betreiber im Adminbereich.</p>{d.focus&&d.pendingSimilarity>0&&<p className="analysis-notice">{d.focusPending?'Für den gewählten Vergleichsartikel fehlen gespeicherte Themenmerkmale. Der Vergleich steht noch aus.':`Für ${d.pendingSimilarity} Vorgänge im Zeitraum fehlen Vergleichsmerkmale. Die Trefferliste umfasst nur bereits analysierte Artikel.`}</p>}
 <nav className="analysis-jumps" aria-label="Abschnitte der Auswertung"><a href="#analysebeispiele">Beispiele</a><a href="#themenverteilung">Verteilung</a><a href="#zeitverlauf">Zeitverlauf</a><a href="#themenmix">Themenmix</a><a href="#ortsvergleich">Karte & Orte</a></nav><AnalysisExamples data={d} active={params.get('example')||'schwerpunkte'}/><div className="analysis-grid"><section id="themenverteilung" className="analysis-panel"><h2>Themenverteilung</h2><p className="page-note">Ein Hauptlabel je Vorgang. Zusammen 100 % einschließlich offener Zuordnungen.</p>{d.total?<div className="distribution">{d.distribution.map((l:any)=><a key={l.id} className={'distribution-row'+(l.id===d.label?' is-selected':'')} href={'/analysen?'+new URLSearchParams({region:d.region,from:d.from,to:d.to,label:l.id,level:d.level})}><span className="distribution-name">{l.name}</span><span className="distribution-value">{l.count} · {fmt(l.share)}</span><span className="distribution-track"><span style={{width:l.share+'%',background:l.color}}/></span></a>)}</div>:<p className="empty-state">Für diesen Zeitraum liegen keine datierten Vorgänge vor.</p>}<AnalysisArticleList key={params.toString()+':local'} query={analysisListQuery(d)} scope="local" title="Erfasste Vorgänge ansehen" total={d.total}/></section>
 <section id="zeitverlauf" className="analysis-panel"><h2>Entwicklung über die Zeit</h2><p><strong>{labelName(d.label)}</strong> · Anteil am jeweiligen Monatsbestand</p><div className="table-scroll trend-scroll" tabIndex={0} role="region" aria-label="Zeitdiagramm, bei Bedarf seitlich scrollen"><Trend months={d.months} color={color}/></div><div className="table-scroll" tabIndex={0} role="region" aria-label="Analysetabelle, bei Bedarf seitlich scrollen"><table className="analysis-table"><thead><tr><th>Monat</th><th>Vorgänge</th><th>Anteil</th><th>Datenlage</th></tr></thead><tbody>{d.months.map((m:any)=><tr key={m.month}><th>{m.month}</th><td>{m.count} / {m.total}</td><td>{fmt(m.share)}</td><td>{!m.total?'Keine Daten':m.partial?'Teilstand':'Erfasster Bestand'}</td></tr>)}</tbody></table></div><p className="page-note">Ein Vorgang kann in mehreren Monaten vorkommen. Monate ohne Vorgänge bleiben als Lücke sichtbar. {d.undated} Vorgänge ohne Sitzungstermin sind ausgeschlossen; {d.future} Vorgänge haben angekündigte zukünftige Termine.</p></section></div>
 <MonthlyMix data={d}/><section id="ortsvergleich" className="analysis-panel map-panel"><div className="map-heading"><div><p className="eyebrow">KARTE & ORTE</p><h2>Orte im Vergleich</h2><p>Sechs Ansichten für Themen, Veränderungen und Datenlage.</p></div></div><DeferredMap availability={d.regionAvailability} key={d.region+':'+d.level} places={mapPlaces(d)} region={d.region} topicMode={!!d.focus} comparisonPeriods={d.comparisonPeriods} subject={d.focus?d.focus.title:labelName(d.label)} from={d.from} to={d.to}/><p className="page-note">Die Deutschlandkarte zeigt die Lage der erfassten Gebiete. Außerhalb der angebundenen Orte liegen keine politischen Daten vor. Städte und Kreise haben unterschiedliche Zuständigkeiten und werden separat gezählt.</p><p className="page-note">{d.places.filter((r:any)=>!r.total).length} weitere Gebiete ohne auswertbare Vorgänge im Zeitraum. <a href={'/quellen?region='+d.region}>Quellenstand prüfen</a></p><div className="map-matches-heading"><h3>{d.focus?'Ähnliche Vorgänge zum Vergleichsartikel':'Treffer zum gewählten Sachgebiet'}</h3><p>{d.focus?d.focus.title:labelName(d.label)} · {d.focusPending?'Vergleich ausstehend':`${d.matchingTopics} Treffer in ${d.matchingPlaces} anderen Gebieten`}.  Diese Liste bleibt auf das gewählte Thema bezogen.</p></div>{!d.focusPending&&d.places.filter((r:any)=>r.total>0).map((r:any)=><AnalysisArticleList key={params.toString()+':'+r.id} id={'place-'+r.id} query={analysisListQuery(d)} target={r.id} total={r.count||0} title={r.name+': '+(r.count||0)+' Treffer'}/>)}</section>
 <details id="datengrundlage" open={params.get('example')==='datenlage'} className="analysis-method"><summary>Wie Labels und Vergleiche entstehen</summary><p>Bei einem manuell gestarteten Analyselauf werden 13 Sachgebiete anhand eindeutiger Begriffe im Originaltitel zugeordnet. Die Ergebnisse und Themenmerkmale werden gespeichert. Neue oder geänderte Titel warten bis zum nächsten ausdrücklichen Start. Allgemeine Anfragen & Mitteilungen sowie Sitzungsablauf & Gremienarbeit bilden zwei zusätzliche Gruppen ohne eigenes Sachgebiet. Alle Gruppen und offene Einordnungen bleiben im Nenner der Prozentanteile. Kultur sowie Sport & Freizeit sind getrennt. Bei Mehrdeutigkeit bleibt die Einordnung offen. Die Zuordnung ist eine erste regelbasierte Einordnung, keine redaktionell bestätigte Inhaltsanalyse.</p><p>Die Kartenansichten Themenanteil, Anzahl und Veränderung beziehen sich auf das gewählte Hauptlabel oder auf ähnliche Vorgänge zum gewählten Artikel. Die Ansichten häufigstes Sachgebiet, offene Labels und Datenabdeckung beziehen sich auf den gesamten Bestand im Zeitraum. Beim Artikelvergleich werden ausschließlich gespeicherte Sachthemen und Titelbegriffe verglichen; ein gemeinsames Hauptlabel allein reicht nicht.</p><p>Maßgeblich ist der Sitzungstag, nicht der Importzeitpunkt. Gezählt werden unterschiedliche Vorgangs-IDs pro Zeitraum und Gebiet. Zukunftstermine sind ausgeschlossen. Fehlende Daten bedeuten keine Nullaktivität. Katalog: {d.version}; Vergleich: {d.matchVersion}. Berechnete Auswertungen werden höchstens 30 Sekunden zwischengespeichert.</p><a href={'/quellen?region='+d.region}>Quellen und Grenzen</a></details></main><Footer active="analysen" region={d.region}/></div>
}
