import fs from 'node:fs/promises';
import {LABELS} from '../../shared/labels.mjs';
import {comparisonMetrics,validPrediction} from '../../shared/label-study.mjs';
const folder=process.argv[2]||'tmp/label-study';const {manifest,rows}=JSON.parse(await fs.readFile(folder+'/corpus.json','utf8'));
const latest=new Map();try{for(const l of (await fs.readFile(folder+'/predictions.jsonl','utf8')).trim().split('\n').filter(Boolean)){const p=JSON.parse(l);latest.set(p.id,p);}}catch(e){if(e.code!=='ENOENT')throw e;}
let stale=0;const models=new Set();
for(const r of rows){const p=latest.get(r.id);if(!p)continue;if(p.inputHash!==r.inputHash||p.promptVersion!==manifest.promptVersion){stale++;continue;}if(p.status==='done'&&!validPrediction(p,r.input))throw Error('Ungültiges gespeichertes KI-Ergebnis: '+r.id);r.ai=p;if(p.status==='done')models.add(p.model);}
if(models.size>1)throw Error('Gemischte Modelle: getrennte Studien auswerten.');
const references=JSON.parse(await fs.readFile(folder+'/references.json','utf8'));
const seen=new Set();for(const r of references){if(seen.has(r.id))throw Error('Doppelte Referenz-ID');seen.add(r.id);if(r.status==='adjudicated'&&(!LABELS.some(l=>l.id===r.primary)||!r.reviewer||!r.reason))throw Error('Freigegebene Referenz braucht gültiges Label, Prüfer und Begründung: '+r.id);}
const metrics={manifest,...comparisonMetrics(rows,references),stalePredictions:stale,model:[...models][0]||null};await fs.writeFile(folder+'/metrics.json',JSON.stringify(metrics,null,2));
const q=s=>{let v=String(s??'');if(/^\s*[=+@-]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"';};
await fs.writeFile(folder+'/labelvergleich.csv','id,gebiet,originaltitel,originalquelle,input_hash,textbasis,regel_label,ki_status,ki_label,ki_modell,uebereinstimmung\n'+rows.map(r=>[r.id,r.regionId,r.input.title,r.sourceUrl,r.inputHash,r.input.basis,r.rule.primary,r.ai.status,r.ai.primary||'',r.ai.model||'',r.ai.status==='done'?String(r.rule.primary===r.ai.primary):''].map(q).join(',')).join('\n')+'\n');
const percent=n=>n===null?'Noch nicht messbar':(100*n).toFixed(1)+' %';
await fs.writeFile(folder+'/vergleich.md',`# Regelbasierte und KI-basierte Labels\n\nStand: ${manifest.createdAt}\n\n${manifest.provenance}\n\n- Artikel: ${metrics.total}\n- Regellabel vorhanden: ${metrics.total}\n- Regelbasiert offen: ${metrics.ruleOpen} (${(100*metrics.ruleOpen/metrics.total).toFixed(1)} %)\n- KI abgeschlossen: ${metrics.aiDone}\n- KI ausstehend: ${metrics.aiPending}\n- KI-Fehler: ${metrics.aiErrors}\n- Übereinstimmung: ${percent(metrics.agreement)}\n- Freigegebene Referenzartikel: ${metrics.referenceCount}\n- Gemeinsame Vergleichsstichprobe: ${metrics.pairedReferenceCount}\n- Genauigkeit Regeln (gepaart): ${percent(metrics.rulePaired.accuracy)}\n- Genauigkeit KI (gepaart): ${percent(metrics.aiPaired.accuracy)}\n\nÜbereinstimmung ist keine Genauigkeit. Beide Verfahren werden auf derselben unabhängig bewerteten Stichprobe verglichen. Fehlende KI-Ergebnisse zählen nicht als Label „unklar“; KI-Abdeckung und Ausfälle werden getrennt ausgewiesen. Der Stichprobenwert wird nicht als gesicherte Genauigkeit jedes einzelnen Labels oder Artikels ausgegeben.\n\nTextbasis: ${manifest.basis}. Regeln verwenden Originaltitel. Im Modus source erhält die KI zusätzlich vorhandene Originalauszüge bzw. bereits extrahierte Dokumenttexte, niemals generierte Zusammenfassungen. Das misst die Produktionsverfahren mit unterschiedlicher Informationsbasis. Für einen Vergleich mit gleicher Textbasis eine eigene Studie mit basis title erstellen. Fehlende PDF-Texte werden nicht automatisch als gelesene Volltexte ausgegeben.\n`);
console.log(JSON.stringify({total:metrics.total,ruleOpen:metrics.ruleOpen,aiDone:metrics.aiDone,referenceCount:metrics.referenceCount}));
