import {getRelated} from '@/server/repositories/regions';
import {REGIONS,regionName} from '@/shared/regions';
import {STATUS,formatDate,type TopicDetail,type TopicStatus} from '@/shared/types';
export async function RelatedTopics({topic}:{topic:TopicDetail}){
 const r=await getRelated(topic);const eligible=REGIONS.filter(x=>x.kind==='district'&&x.id!==REGIONS.find(x=>x.id===topic.regionId)?.district);const missing=eligible.filter(x=>!r.coverage.some((c:any)=>c.regionId===x.id&&c.complete));
 if(r.analysisPending)return <section className="related-topics" id="vergleich"><h2 className="heading-m">Ähnliche Themen in anderen Kreisen</h2><p>Analyse ausstehend. Themenmerkmale werden erst auf ausdrückliche Anforderung des Betreibers erstellt.</p></section>;
 return <section className="related-topics" id="vergleich"><h2 className="heading-m">Ähnliche Themen in anderen Kreisen</h2><p className="related-count">In <strong>{r.totalDistricts.length}</strong> von {eligible.length} anderen Kreisen gefunden</p><div className="comparison-counts"><div><strong>{r.currentDistricts.length}</strong><span>aktuell / offen</span></div><div><strong>{r.historicalDistricts.length}</strong><span>früher erfasst / abgeschlossen</span></div></div><p className="page-note">Vergleich gespeicherter Themenmerkmale, keine Aussage über identische Beschlüsse. Ein Kreis kann in mehreren Zeitgruppen vorkommen und zählt insgesamt nur einmal.</p>{r.pendingComparisons>0&&<p className="page-note">Für {r.pendingComparisons} Vergleichsartikel stehen Themenmerkmale noch aus. Diese sind nicht in den Treffern enthalten.</p>}{!r.storageAvailable&&<p role="status">Datenbank nicht erreichbar: Vergleich aus gespeichertem Ersatzstand.</p>}{missing.length>0&&<details className="comparison-warning"><summary>Datenlücken in {missing.length} Kreisen</summary><p>{missing.map(x=>x.name).join(', ')}. Die Zahlen sind keine vollständige Erhebung.</p></details>}
 {(['current','historical','unclear'] as const).map(period=><div key={period}><h3>{period==='current'?'Aktuell / offen':period==='historical'?'Früher erfasst / abgeschlossen':'Zeitliche Einordnung offen'}</h3>{!r.matches.some((m:any)=>m.period===period)?<p className="page-note">Keine hinreichend ähnlichen Artikel im verfügbaren Bestand gefunden.</p>:eligible.filter(region=>r.matches.some((m:any)=>m.period===period&&m.regionId===region.id)).map(region=><details className="related-group" key={region.id}><summary>{region.name} · {r.matches.filter((m:any)=>m.period===period&&m.regionId===region.id).length} Vorgänge</summary>{r.matches.filter((m:any)=>m.period===period&&m.regionId===region.id).map((m:any)=><article className="related-item" key={m.id}><a href={'/thema/'+m.id}>{m.title}</a><p>{formatDate(m.eventDate)} · {STATUS[m.status as TopicStatus].label}</p><p>{m.reason}</p><a className="text-link" href={m.sourceUrl} target="_blank" rel="noopener noreferrer">Originalquelle</a></article>)}</details>)}</div>)}
 <details className="related-method"><summary>Wie wird verglichen?</summary><p>Verglichen werden die Originaltitel der Artikel aus den angebundenen Kreisen. Übereinstimmende konkrete Sachthemen oder mindestens zwei prägende Titelbegriffe begründen einen Treffer. Eine gemeinsame Rubrik allein reicht nicht.</p><p>Aktuell: angekündigter, beratener, empfohlener oder vertagter Vorgang mit einem Termin innerhalb von 90 Tagen vor oder nach heute. Früher: dokumentiertes Ergebnis oder letzter Termin vor mehr als 90 Tagen. Unklare Stände und weiter entfernte Termine werden separat angezeigt. Das ist eine rechnerische Einordnung, kein Beleg für laufende Beratungen außerhalb der Quellen.</p><p>Verfahren: {r.method}. Ausgangsbestand: drei Monate; ältere gespeicherte Artikel bleiben erhalten. Der eigene Kreis wird ausgeschlossen. Stadtartikel werden nicht als Kreisentscheidungen gezählt.</p><a href="/quellen">Quellenstand je Gebiet</a></details></section>
}
