import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import Link from 'next/link';
import type {TopicDetail} from '@/shared/types';
import {STATUS,formatDate} from '@/shared/types';
import {REGIONS} from '@/shared/regions';
import {SessionDetails} from '@/components/article-analysis';
import {IconChevronLeft,IconDoc} from '../components/icons';
import {useAppNav} from '../state/nav';
import {ShareButton} from '../components/ShareButton';
import {SaveArticleButton} from '../components/SaveArticleButton';
import {FollowButton} from '../components/FollowButton';
export function DetailPage(){
 const params=useParams(),id=String(params.id||''),{goBack}=useAppNav();
 const [data,setData]=useState<{id:string;topic:TopicDetail|null;error:string}>({id:'',topic:null,error:''}),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const ctrl=new AbortController();fetch('/api/topics/'+encodeURIComponent(id),{signal:ctrl.signal}).then(async r=>{if(!r.ok)throw Error(r.status===404?'Dieser Vorgang wurde nicht gefunden.':'Der Vorgang konnte nicht geladen werden.');return r.json() as Promise<TopicDetail>;}).then(t=>{if(!ctrl.signal.aborted)setData({id,topic:t,error:''});}).catch(e=>{if(!ctrl.signal.aborted)setData({id,topic:null,error:e.message});});window.scrollTo(0,0);return()=>ctrl.abort();},[id,attempt]);
 const t=data.id===id?data.topic:null,region=REGIONS.find(r=>r.id===t?.regionId);
 if(!t)return <main id="inhalt" className="mx-auto max-w-page py-[max(0.3vw,6px)]"><Link className="link-btn" href="/">Zur Übersicht</Link>{data.id===id&&data.error?<div role="alert" className="card-shell mt-6 p-6"><p>{data.error}</p><button className="btn-secondary mt-4" onClick={()=>setAttempt(n=>n+1)}>Erneut versuchen</button></div>:<p role="status" className="mt-6">Vorgang wird geladen …</p>}</main>;
 const host=(u:string)=>{try{return new URL(u).host;}catch{return '';}},events=t.events.filter(e=>!t.sourceUrl||!e.url||!host(e.url)||host(e.url)===host(t.sourceUrl)),status=STATUS[t.status]||STATUS.unknown;
 return <main id="inhalt" className="mx-auto max-w-page py-[max(0.3vw,6px)]"><article className="card-shell px-3 py-4 sm:px-4 sm:py-5">
 <button className="back-btn mb-5" onClick={goBack}><IconChevronLeft/>Zurück zur Übersicht</button>
 <div className="flex flex-wrap items-center gap-2 text-xs"><span className="chip-soft">{region?.name||'Gebiet nicht zugeordnet'}</span><span className="chip-soft">{t.category}</span><span className="rounded-full border border-teal-200 bg-teal-50 px-3 py-1 font-semibold text-teal-800">{status.label}</span><ShareButton title={t.title} url={typeof window!=='undefined'?window.location.origin+'/beschluss/'+t.id:''} className="ml-auto"/><FollowButton article={{id:t.id,title:t.title,date:(t.eventDate||'').slice(0,10),gemeinde:region?.name||'',teaser:t.shortSummary||''}} size={22}/><SaveArticleButton article={{id:t.id,title:t.title,date:(t.eventDate||'').slice(0,10),gemeinde:region?.name||'',teaser:t.shortSummary||''}} size={22}/></div>
 <h1 className="mb-4 mt-5 text-3xl font-bold leading-tight tracking-tight">{t.title}</h1><p className="text-lg leading-relaxed text-slate-600">{t.shortSummary}</p>
 <dl className="my-7 grid grid-cols-2 gap-4 border-y border-slate-200 py-5 text-sm sm:grid-cols-3">{[['Sitzung',formatDate(t.eventDate)],['Gremium',t.committee||'Nicht dokumentiert'],['Vorlage',t.reference||'Nicht dokumentiert'],['Quellenstand',formatDate(t.updatedAt)],['Gebiet',region?.name||'Unbekannt'],['Verfahrensstand',status.label]].map(([k,v])=><div key={k}><dt className="mb-1 text-xs text-slate-500">{k}</dt><dd className="font-medium">{v}</dd></div>)}</dl>
 <section><h2 className="mb-3 text-xl font-semibold">{t.contentAnalysis?.status==='completed'?'Inhaltszusammenfassung':'Gespeicherter Quellenüberblick'}</h2>{t.longSummary?.map((p,i)=><p key={i} className="mb-4 text-base leading-relaxed text-slate-700">{p}</p>)}<p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-600">{status.description}</p></section>
 <section className="mt-6"><h2 className="mb-2 text-lg font-semibold">Verlauf & Sitzungen</h2>{events.length?<ol className="divide-y divide-slate-200 rounded-lg border border-slate-200 text-sm">{events.map((e,i)=><li key={i} className="px-3 py-1.5"><div className="flex flex-wrap items-baseline gap-x-2"><time className="w-[84px] shrink-0 tabular-nums text-slate-500">{formatDate(e.date)}</time><strong className="font-medium">{e.committee||'Gremium nicht dokumentiert'}</strong><span className="text-slate-500">· {STATUS[e.status]?.label||'Stand offen'}</span>{e.url&&<a className="ml-auto text-teal-700 no-underline hover:underline" href={e.url} target="_blank" rel="noopener noreferrer" title="Öffentliche Sitzung öffnen">Sitzung ↗</a>}</div>{e.description&&<p className="m-0 text-[13px] text-slate-600 sm:pl-[92px]">{e.description}</p>}<div className="text-[13px] sm:pl-[92px]"><SessionDetails event={e}/></div></li>)}</ol>:<p className="text-sm text-slate-500">Keine öffentliche Sitzung zugeordnet.</p>}</section>
 <section className="mt-6"><h2 className="mb-1 text-lg font-semibold">Originalunterlagen</h2><p className="mb-3 text-sm text-slate-500">Originaltitel: {t.officialTitle}</p><ul className="grid grid-cols-[repeat(auto-fill,minmax(120px,1fr))] gap-3">{t.documents.map((d,i)=><li key={i}><a href={d.url} target="_blank" rel="noopener noreferrer" title={d.title||'Dokument'} className="flex h-full flex-col items-center gap-2 rounded-lg border border-slate-200 bg-white p-3 text-center text-[12.5px] leading-snug text-slate-700 no-underline hover:border-teal-200 hover:bg-teal-50 hover:text-teal-700"><IconDoc size={40} strokeWidth={1.5}/><span className="line-clamp-3 break-words">{d.title||'Dokument'}</span></a></li>)}</ul>{!t.documents.length&&<p className="text-sm text-slate-500">Keine Unterlagen verlinkt.</p>}{t.sourceUrl&&<a className="link-btn mt-3 inline-block" href={t.sourceUrl} target="_blank" rel="noopener noreferrer">Vorgang im Ratsinformationssystem ↗</a>}</section>

 </article></main>;
}
