'use client';
import {useEffect,useId,useState} from 'react';
import type {AdminSource} from '@/shared/admin-types';
type Geo={regionViewBox:string;source:string;regions:{id:string;ags:string;kind:string;path:string;bounds:number[]}[]};
// Ausschnitt eines Landes: Umriss seiner Gebiete mit Rand; ohne Land der Ausschnitt aller Gebiete.
function viewBox(geo:Geo,land:string){const rs=geo.regions.filter(r=>r.ags.startsWith(land));if(land==='all'||!rs.length)return geo.regionViewBox;const b=[Math.min(...rs.map(r=>r.bounds[0]))-6,Math.min(...rs.map(r=>r.bounds[1]))-6,Math.max(...rs.map(r=>r.bounds[2]))+6,Math.max(...rs.map(r=>r.bounds[3]))+6];return b[0]+' '+b[1]+' '+(b[2]-b[0])+' '+(b[3]-b[1]);}
export function AdminProcessingMap({sources,selected,onToggle,layer,mode,land='all'}:{sources:AdminSource[];selected:Set<string>;onToggle:(id:string)=>void;layer:string;mode:string;land?:string}){
 const [geo,setGeo]=useState<Geo|null>(null),[error,setError]=useState(false),[hover,setHover]=useState<string|null>(null);const pattern='admin-map-'+useId().replaceAll(':','');
 useEffect(()=>{const c=new AbortController();fetch('/geo/germany.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<Geo>;}).then(setGeo).catch(e=>{if(e.name!=='AbortError')setError(true);});return()=>c.abort();},[]);
 const byId=new Map(sources.map(s=>[s.id,s]));
 const color=(s:AdminSource)=>{if(mode==='coverage')return !s.canImport&&!s.count?'#e4e7eb':s.attemptStatus==='failed'?'#ad392d':!s.canImport?'#e4e7eb':!s.count?'#f2ce82':s.partial?'#99f6e4':'#0d9488';if(!s.count)return `url(#${pattern})`;const amount=mode==='count'?Math.log10(s.count+1)/Math.log10(Math.max(2,...sources.map(s=>s.count))+1):Number(s.processing[mode as keyof typeof s.processing]||0)/s.count;return amount>.8?'#0f766e':amount>.5?'#0d9488':amount>.2?'#72d4ca':'#b9eae4';};
 const h=hover?byId.get(hover):null;
 return <div className="admin-map"><div className="admin-map-canvas">{error?<p role="alert">Karte nicht verfügbar. Alle Gebiete lassen sich in der Liste auswählen.</p>:!geo?<p role="status">Karte wird geladen …</p>:<svg viewBox={viewBox(geo,land)} aria-label="Gebiete durch Klicken auswählen; dieselbe Auswahl ist in der Liste erreichbar." role="img"><defs><pattern id={pattern} width="5" height="5" patternUnits="userSpaceOnUse"><rect width="5" height="5" fill="#f5f5f5"/><path d="M0 5L5 0" stroke="#aab1bc" strokeWidth=".5"/></pattern></defs>{geo.regions.filter(r=>r.kind===layer&&byId.has(r.id)&&(land==='all'||r.ags.startsWith(land))).sort((a,b)=>Number(selected.has(a.id))-Number(selected.has(b.id))).map(r=>{const s=byId.get(r.id)!;return <path key={r.id} d={r.path} fill={color(s)} stroke={selected.has(r.id)?'#101d37':'#fff'} strokeWidth={selected.has(r.id)?2.2:.55} vectorEffect="non-scaling-stroke" onClick={()=>onToggle(r.id)} onMouseEnter={()=>setHover(r.id)} onMouseLeave={()=>setHover(null)} className="admin-map-region"><title>{s.name+': '+s.count+' Berichte. '+s.state+(selected.has(r.id)?'. Ausgewählt':'')}</title></path>;})}</svg>}</div><p className="admin-map-hover" aria-live="polite">{h?<><strong>{h.name}</strong> · {h.count.toLocaleString('de-DE')} Berichte · {h.state}</>:<>Dunkle Umrandung: ausgewählt · Auswahl per Karte oder Liste</>}</p><div className="admin-map-legend">{(mode==='coverage'?[['#0d9488','Daten vorhanden'],['#99f6e4','Teilbestand'],['#ad392d','Abruf fehlgeschlagen'],['#f2ce82','Angebunden, ohne Daten'],['#e4e7eb','Nicht angebunden']]:[['#b9eae4','Wenig / 0'],['#72d4ca','Mehr'],['#0f766e','Viel / vollständig']]).map(([c,t])=><span key={t}><i style={{background:c}}/>{t}</span>)}</div><small>© BKG (2026), <a href="https://www.govdata.de/dl-de/by-2-0" target="_blank" rel="noreferrer">dl-de/by-2-0</a>. Gemeinden NRW und Niedersachsen (Samtgemeinden): VG250, Kreise: VG2500 bzw. VG250 (Niedersachsen). {mode!=='coverage'&&'Helle Farbe bei vorhandenem Bestand bedeutet 0, Schraffur bedeutet keine Berichte.'}</small></div>;
}
