'use client';
import {useEffect,useId,useState} from 'react';
import type {AdminSource} from '@/shared/admin-types';
type Geo={regionViewBox:string;source:string;regions:{id:string;kind:string;path:string}[]};
export function AdminProcessingMap({sources,selected,onToggle,layer,mode}:{sources:AdminSource[];selected:Set<string>;onToggle:(id:string)=>void;layer:string;mode:string}){
 const [geo,setGeo]=useState<Geo|null>(null),[error,setError]=useState(false),[hover,setHover]=useState<string|null>(null);const pattern='admin-map-'+useId().replaceAll(':','');
 useEffect(()=>{const c=new AbortController();fetch('/geo/germany.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<Geo>;}).then(setGeo).catch(e=>{if(e.name!=='AbortError')setError(true);});return()=>c.abort();},[]);
 const byId=new Map(sources.map(s=>[s.id,s]));
 const color=(s:AdminSource)=>{if(mode==='coverage')return s.attemptStatus==='failed'?'#ad392d':!s.canImport?'#e4e7eb':!s.count?'#f2ce82':s.partial?'#9bb7eb':'#2352ad';if(!s.count)return `url(#${pattern})`;const amount=mode==='count'?Math.log10(s.count+1)/Math.log10(Math.max(2,...sources.map(s=>s.count))+1):Number(s.processing[mode as keyof typeof s.processing]||0)/s.count;return amount>.8?'#193f8c':amount>.5?'#3e6dc2':amount>.2?'#82a6e1':'#d5e2f7';};
 const h=hover?byId.get(hover):null;
 return <div className="admin-map"><div className="admin-map-canvas">{error?<p role="alert">Karte nicht verfügbar. Alle Gebiete lassen sich in der Liste auswählen.</p>:!geo?<p role="status">Karte wird geladen …</p>:<svg viewBox={geo.regionViewBox} aria-label="NRW: Gebiete durch Klicken auswählen; dieselbe Auswahl ist in der Liste erreichbar." role="img"><defs><pattern id={pattern} width="5" height="5" patternUnits="userSpaceOnUse"><rect width="5" height="5" fill="#f5f5f5"/><path d="M0 5L5 0" stroke="#aab1bc" strokeWidth=".5"/></pattern></defs>{geo.regions.filter(r=>r.kind===layer&&byId.has(r.id)).sort((a,b)=>Number(selected.has(a.id))-Number(selected.has(b.id))).map(r=>{const s=byId.get(r.id)!;return <path key={r.id} d={r.path} fill={color(s)} stroke={selected.has(r.id)?'#101d37':'#fff'} strokeWidth={selected.has(r.id)?2.2:.55} vectorEffect="non-scaling-stroke" onClick={()=>onToggle(r.id)} onMouseEnter={()=>setHover(r.id)} onMouseLeave={()=>setHover(null)} className="admin-map-region"><title>{s.name+': '+s.count+' Berichte. '+s.state+(selected.has(r.id)?'. Ausgewählt':'')}</title></path>;})}</svg>}</div><p className="admin-map-hover" aria-live="polite">{h?<><strong>{h.name}</strong> · {h.count.toLocaleString('de-DE')} Berichte · {h.state}</>:<>Dunkle Umrandung: ausgewählt · Auswahl per Karte oder Liste</>}</p><div className="admin-map-legend">{(mode==='coverage'?[['#2352ad','Daten vorhanden'],['#9bb7eb','Teilbestand'],['#ad392d','Abruf fehlgeschlagen'],['#f2ce82','Angebunden, ohne Daten'],['#e4e7eb','Nicht angebunden']]:[['#d5e2f7','Wenig / 0'],['#82a6e1','Mehr'],['#193f8c','Viel / vollständig']]).map(([c,t])=><span key={t}><i style={{background:c}}/>{t}</span>)}</div><small>© BKG (2026), <a href="https://www.govdata.de/dl-de/by-2-0" target="_blank" rel="noreferrer">dl-de/by-2-0</a>. NRW-Gemeinden: VG250, Kreise: VG2500. {mode!=='coverage'&&'Helle Farbe bei vorhandenem Bestand bedeutet 0, Schraffur bedeutet keine Berichte.'}</small></div>;
}
