'use client';
import {DatabaseAdmin} from '@/components/database-admin';
import {AdminQualityCheck} from '@/components/admin-quality-check';
import {useEffect,useMemo,useRef,useState} from 'react';
import {RefreshCw,ArrowUpRight,AlertCircle,Check} from 'lucide-react';
import {AdminHeader,adminHref} from '@/components/admin-chrome';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {REVIEW_FILTERS} from '@/shared/admin.mjs';
import {regionName} from '@/shared/regions';
import {STATUS} from '@/shared/types';
import type {AdminDashboard,AdminSource} from '@/shared/admin-types';
const n=(v:number)=>v.toLocaleString('de-DE');
const date=(s:string|null)=>s?new Date(s).toLocaleString('de-DE',{timeZone:'Europe/Berlin',dateStyle:'short',timeStyle:'short'}):'Noch kein Abruf';
const pct=(a:number,b:number)=>b?(100*a/b).toLocaleString('de-DE',{maximumFractionDigits:1})+' %':'—';
function Choice({id,label,value,onChange,items}:{id:string;label:string;value:string;onChange:(value:string)=>void;items:{id:string;name:string}[]}){return <div className="admin-field"><label id={id+'-label'}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger aria-labelledby={id+'-label'}><SelectValue/></SelectTrigger><SelectContent position="popper">{items.map(item=><SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div>}
/** Admin page "Qualität & Betrieb": content quality, import runs, database, operations. Reads; the older tools are folded away. */
export function AdminDashboardView({initial,displayName,signOutPath}:{initial:AdminDashboard;displayName:string;signOutPath:string}){
 const [data,setData]=useState(initial),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [issue,setIssue]=useState('labels'),[reviewRegion,setReviewRegion]=useState('all'),[review,setReview]=useState(initial.review),[reviewBusy,setReviewBusy]=useState(false),[reviewError,setReviewError]=useState('');
 const [analysisRegion,setAnalysisRegion]=useState('all'),[analysing,setAnalysing]=useState('');
 const firstReview=useRef(true);
 const populated=useMemo(()=>data.sources.filter(s=>s.count>0),[data.sources]),partial=populated.filter(s=>s.partial),stale=populated.filter(s=>s.stale),configuredEmpty=data.sources.filter(s=>s.canImport&&!s.count),failed=data.sources.filter(s=>s.attemptStatus==='failed');
 useEffect(()=>{
  if(firstReview.current){firstReview.current=false;return;}
  const controller=new AbortController();setReviewBusy(true);setReviewError('');
  fetch('/api/admin/review?'+new URLSearchParams({issue,region:reviewRegion}),{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json() as AdminDashboard['review'] & {error?:string};if(!r.ok)throw Error(d.error||'Prüfliste nicht erreichbar.');return d;}).then(setReview).catch(e=>{if(e.name!=='AbortError')setReviewError(e.message);}).finally(()=>{if(!controller.signal.aborted)setReviewBusy(false);});
  return ()=>controller.abort();
 },[issue,reviewRegion,data.asOf]);
 async function refresh(preserveError=false){setRefreshing(true);if(!preserveError)setError('');try{const r=await fetch('/api/admin/overview',{cache:'no-store'}),d=await r.json() as AdminDashboard & {error?:string};if(!r.ok)throw Error(d.error||'Aktualisierung fehlgeschlagen.');setData(d);}catch(e){setError(e instanceof Error?e.message:'Aktualisierung fehlgeschlagen.');}finally{setRefreshing(false);}}
 async function startAnalysis(mode:'analysis'|'summaries'){
  setAnalysing(mode);setMessage('');setError('');
  try{const r=await fetch('/api/admin/analyse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({region:analysisRegion,mode}),signal:AbortSignal.timeout(160000)}),d=await r.json() as {error?:string;processed?:number;remaining?:number;more?:boolean};if(!r.ok)throw Error(d.error||'Analyse fehlgeschlagen.');setMessage(mode==='analysis'?n(d.processed||0)+' Artikel analysiert. '+n(d.remaining||0)+' stehen in dieser Auswahl noch aus. Ein weiterer Lauf startet erst mit deinem nächsten Klick.':n(d.processed||0)+' Artikel zur Textverarbeitung übernommen. Ergebnisse und Hinweise stehen im Importverlauf.');}catch(e){setError(e instanceof Error&&e.name!=='TimeoutError'?e.message:'Die Antwort dauert länger. Bitte zuerst den Verlauf aktualisieren; es wird kein weiterer Lauf automatisch gestartet.');}finally{setAnalysing('');await refresh(true);}
 }
 async function importPrepared(){
  setAnalysing('prepared');setError('');setMessage('');
  try{const r=await fetch('/api/admin/prepared-analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}),d=await r.json() as {error?:string;processed:number;skipped:number;remaining:number;conflicts:number};if(!r.ok)throw Error(d.error||'Übernahme fehlgeschlagen.');setMessage(n(d.processed)+' Billerbeck-Ergebnisse gespeichert · '+n(d.skipped)+' bereits vorhanden · '+n(d.remaining)+' noch ausstehend · '+n(d.conflicts)+' Abweichungen zum vorbereiteten Datenstand. Jeder weitere Lauf benötigt einen Klick.');}catch(e){setError(e instanceof Error?e.message:'Übernahme fehlgeschlagen.');}finally{setAnalysing('');await refresh(true);}
 }
 const busy=!!analysing||!!data.importBusyUntil,restore=data.processing.restore;
 return <div className="admin-app"><AdminHeader page="qualitaet" displayName={displayName} signOutPath={signOutPath}/><main id="inhalt" className="admin-shell">
  <div className="admin-heading"><div><p className="eyebrow">QUALITÄT & BETRIEB</p><h1>Was braucht einen zweiten Blick?</h1><p>{displayName} · Datenbankstand {date(data.asOf)} Uhr</p></div><Button className="admin-refresh" variant="outline" onClick={()=>refresh()} disabled={refreshing||busy}><RefreshCw size={16} className={refreshing?'admin-spin':''}/>{refreshing?'Wird geladen …':'Aktualisieren'}</Button></div>
  {error&&<p className="admin-error" role="alert">{error} Der letzte geladene Stand bleibt sichtbar.</p>}
  {message&&<p role="status" className="admin-notice">{message}</p>}
  <section className="admin-kpis" aria-label="Bestandskennzahlen">
   <div className="admin-kpi admin-kpi-primary"><span>Artikel online</span><strong>{n(data.counts.online)}</strong><small>Eigenständige Vorgänge im Themenfeed · {n(data.counts.updated7d)} in sieben Tagen aktualisiert</small></div>
   <div className="admin-kpi"><span>Gebiete mit Artikeln</span><strong>{n(populated.length)}<em> / {n(data.sources.length)}</em></strong><small>{n(populated.filter(s=>s.kind==='city').length)} Kommunen · {n(populated.filter(s=>s.kind==='district').length)} Kreise</small></div>
   <a className="admin-kpi" href="#admin-qualitaet" onClick={()=>{setIssue('labels');setReviewRegion('all');}}><span>Label noch offen</span><strong>{pct(data.counts.unlabelled,data.counts.online)}</strong><small>{n(data.counts.unlabelled)} Artikel zur Einordnung</small></a>
   <a className="admin-kpi" href={adminHref('abruf','filter=issues')}><span>Quellen mit Hinweisen</span><strong>{n(partial.length+failed.length)}</strong><small>{n(partial.length)} Teilstände · {n(failed.length)} fehlgeschlagene Abrufe</small></a>
  </section>
  <nav className="admin-nav" aria-label="Abschnitte dieser Seite"><a href="#admin-qualitaet">Inhaltsqualität</a><a href="#admin-importe">Importverlauf</a><a href="#admin-datenbank">Datenbank</a><a href="#admin-betrieb">Betrieb</a><a href="/api/admin/export?filter=all">Quellen als CSV</a><a href="/" target="_blank" rel="noreferrer">Website ansehen <ArrowUpRight size={15}/></a></nav>
  <div className="admin-attention"><AlertCircle size={19}/><div><strong>Als Nächstes prüfen</strong><p><a href={adminHref('abruf','filter=issues')}>{n(partial.length)} Quellen mit Lücken</a> · <a href={adminHref('abruf','filter=issues')}>{n(stale.length)} ältere Datenstände</a> · <a href={adminHref('abruf','filter=empty')}>{n(configuredEmpty.length)} angebundene Quellen ohne Artikel</a> · <a href={adminHref('atlas')}>offene Gebiete im Lückenatlas</a></p></div></div>
  <section id="admin-qualitaet" className="admin-section">
   <div className="admin-section-heading"><div><p className="eyebrow">01 / INHALTSQUALITÄT</p><h2>Prüfliste und Einordnung</h2></div></div>
   <div className="admin-quality-stats"><div><strong>{n(data.counts.aiSummaries)}</strong><span>KI-Zusammenfassungen</span></div><div><strong>{n(data.counts.online-data.counts.aiSummaries)}</strong><span>Ohne aktuelle KI-Kennzeichnung</span></div><div><strong>{n(data.counts.pdfArticles)}</strong><span>Artikel mit PDF-Verweis</span></div><div><strong>{n(data.counts.qualityPassed)}</strong><span>Technische Textprüfung bestanden</span></div></div>
   <div className="admin-quality-stats"><div><strong>{n(data.counts.contentSummaries)}</strong><span>Inhaltsanalysen abgeschlossen</span></div><div><strong>{n(data.counts.summaryInsufficient)}</strong><span>Sachtext unzureichend</span></div><div><strong>{n(data.counts.summaryStale)}</strong><span>Inhaltsanalyse veraltet</span></div><div><strong>{n(data.counts.aiLabels)}</strong><span>Separate KI-Labels</span></div><div><strong>{n(data.counts.weightedKeywords)}</strong><span>Gewichtete Stichwortprofile</span></div></div>
   <p className="admin-note">Technische Prüfungen ersetzen keine unabhängige fachliche Bewertung. Die Labelstatistik zeigt die regelbasierte Einordnung; KI-Labels aus dem Billerbeck-Test werden separat gespeichert und auf den Artikelseiten gegenübergestellt.</p>
   <div className="admin-charts"><div><h3>Thematische Einordnung</h3>{data.labels.filter(l=>l.count>0).sort((a,b)=>b.count-a.count).map(l=><div className="admin-bar-row" key={l.id}><div><span>{l.name}</span><span>{n(l.count)} · {pct(l.count,data.counts.online)}</span></div><div className="admin-bar" aria-hidden="true"><span style={{width:(data.counts.online?100*l.count/data.counts.online:0)+'%'}}/></div></div>)}</div><div><h3>Verfahrensstand</h3>{data.statuses.map(s=><div className="admin-status-row" key={s.id}><span>{STATUS[s.id as keyof typeof STATUS]?.label||'Unbekannt'}</span><strong>{n(s.count)}</strong></div>)}<div className="admin-explainer"><strong>{n(data.counts.updated7d)} Artikel in sieben Tagen aktualisiert</strong><p>Gezählt nach dem gespeicherten Aktualisierungsdatum. Eine neue Übernahme kann auch bereits vorhandene Artikel aktualisieren; dies ist keine Zahl neu entstandener Themen.</p></div></div></div>
   <div className="admin-review-head"><h3>Prüfliste</h3><p>Bis zu 25 zuletzt aktualisierte Treffer. Die Links öffnen den Artikel zur Prüfung.</p></div>
   <div className="admin-source-controls"><Choice id="admin-review-issue" label="Prüfgrund" value={issue} onChange={setIssue} items={REVIEW_FILTERS}/><Choice id="admin-review-region" label="Gebiet" value={reviewRegion} onChange={setReviewRegion} items={[{id:'all',name:'Alle Gebiete mit Artikeln'},...populated.map(s=>({id:s.id,name:s.name}))]}/></div>
   {reviewError?<p role="alert" className="admin-error">{reviewError}</p>:reviewBusy?<p role="status" className="admin-empty">Prüfliste wird geladen …</p>:<><p className="admin-note">{review.total===null?`Die Trefferzahl folgt, sobald ${n(review.pending||0)} geänderte Gebiete nachgerechnet sind. Gezeigt werden Treffer unter den 5.000 zuletzt geänderten Berichten.`:`${n(review.total)} Artikel passen zu dieser Auswahl.`}</p><ol className="admin-review-list">{review.articles.map(a=><li key={a.id}><div><a href={'/thema/'+a.id} target="_blank" rel="noreferrer">{a.title} <ArrowUpRight size={15}/></a><small>{regionName(a.regionId)} · Aktualisiert {date(a.updatedAt)}</small></div></li>)}</ol>{!review.articles.length&&<p className="admin-empty">Keine Treffer für diesen Prüfgrund.</p>}</>}
  </section>
  <section id="admin-importe" className="admin-section"><p className="eyebrow">02 / IMPORTVERLAUF</p><h2>Die letzten Abrufe</h2><p className="admin-note">Die letzten 30 im Backend gestarteten Läufe. Extern eingespielte Nachladungen sind über den Quellenstand dokumentiert.</p>
   {!data.runs.length?<p className="admin-empty">Noch keine Backend-Importläufe protokolliert. Abrufe startest du auf der Seite „Abruf & Verarbeitung“.</p>:<Table className="admin-table"><TableHeader><TableRow><TableHead>Beginn</TableHead><TableHead>Gebiet / Auslöser</TableHead><TableHead>Ergebnis</TableHead><TableHead className="admin-number">Einträge</TableHead></TableRow></TableHeader><TableBody>{data.runs.map(r=><TableRow key={r.id}><TableCell>{date(r.startedAt)}<small>{r.mode==='ai-agent-analysis'?'KI-Agent-Ergebnisse':r.mode==='claude-analysis'?'Claude-Code-Ergebnisse':r.mode==='prepared-analysis'?'Vorbereiteter KI-Test':r.mode==='summaries'?'Textverarbeitung':r.mode==='analysis'?'Labels & Themenmerkmale':'Quellenimport'}</small></TableCell><TableCell>{r.region==='all'?'Alle Gebiete':regionName(r.region)}<small>{r.trigger==='scheduled'?'Geplant':r.trigger==='manual'?'Manuell':'Auslöser nicht erfasst'}</small></TableCell><TableCell><span className={'admin-state'+(['failed','partial'].includes(r.status)||r.abandoned?' needs-attention':'')}>{r.abandoned?'Status offen: länger als 10 Minuten':({completed:'Abgeschlossen',partial:'Teilweise übernommen',failed:'Fehlgeschlagen',running:'Läuft'}[r.status]||r.status)}</span>{r.finishedAt&&<small>Ende {date(r.finishedAt)}</small>}{r.issueCount>0&&<small>{r.issueCount} Hinweise im Quellenstand</small>}</TableCell><TableCell className="admin-number">{r.count===null?'—':n(r.count)}</TableCell></TableRow>)}</TableBody></Table>}
  </section>
  <section className="admin-section admin-storage-status" aria-labelledby="uebernahme"><p className="eyebrow">03 / DATENBANK</p><h2 id="uebernahme">Export und lokale Übernahme</h2>{restore?<p><Check size={17}/> In dieser Datenbank wurde am {date(restore.at)} ein geprüfter Export vom {date(restore.sourceCreatedAt)} übernommen. {restore.localRevision===data.processing.revision?'Seit dieser Übernahme ist die Inhaltsrevision unverändert.':'Seitdem kann der Bestand weiterbearbeitet worden sein; der aktuelle Stand steht oben.'}</p>:<p>In dieser Datenbank ist noch kein Übernahmebeleg hinterlegt. Ein Download bestätigt keine Speicherung auf einem anderen PC.</p>}{data.processing.lastAiApply&&<p>Letzter geprüfter KI-Import: {date(data.processing.lastAiApply.at)} · {data.processing.lastAiApply.applied} gespeichert · {data.processing.lastAiApply.conflicts.length} Konflikte.</p>}<p className="admin-note">Lokal speichern Abruf und Analysen direkt in der lokalen Datenbank. Für die Übertragung aus dem Online-System: Export herunterladen, mit dem Wiederherstellungswerkzeug lokal einlesen und diese Seite lokal öffnen (README, „Vollständige Datenbank lokal übernehmen“).</p></section>
  <DatabaseAdmin sources={data.sources} disabled={busy}/>
  <AdminQualityCheck sources={data.sources} disabled={busy}/>
  <section id="admin-betrieb" className="admin-section"><p className="eyebrow">04 / BETRIEB</p><h2>Was ist eingerichtet?</h2><dl className="admin-operations"><div><dt>Datenbank</dt><dd>Erreichbar · Revision {n(data.processing.revision)} · {n(data.counts.versions)} archivierte Fassungen · {n(data.counts.analysisVersions)} Analysefassungen · {n(data.counts.aliases)} zusammengeführte Verweise</dd></div><div><dt>Automatische Importe</dt><dd>{data.lastScheduledAt?'Letzter protokollierter geplanter Start: '+date(data.lastScheduledAt):'Kein geplanter Lauf protokolliert'}<small>Ein manueller Abruf aktiviert keinen Zeitplan. Ein früherer Lauf bestätigt keine dauerhaft aktive Planung.</small></dd></div><div><dt>Laufende KI-Zusammenfassungen</dt><dd>{data.operations.aiConfigured?'API-Zugang eingerichtet':'API-Zugang nicht eingerichtet'}<small>Nur ein ausdrücklicher Start verarbeitet neue Texte.</small></dd></div><div><dt>Push für Münster</dt><dd>{data.operations.pushConfigured?'Versand konfiguriert':'Versand nicht konfiguriert'} · {n(data.counts.pushSubscriptions)} gespeicherte Abonnements<small>Ein gespeichertes Abonnement ist kein Nachweis einer zugestellten Nachricht.</small></dd></div><div><dt>Besucherzahlen</dt><dd>Werden bisher nicht erfasst.</dd></div></dl>
   <details className="admin-legacy"><summary>Ältere Werkzeuge</summary><p className="admin-note">Das feste Billerbeck-Testpaket bleibt für frühere Datenstände verfügbar; neue KI-Aufträge werden auf „Abruf & Verarbeitung“ vorbereitet.</p><div className="admin-selection-actions"><Button variant="outline" disabled={busy} onClick={importPrepared}>Vorbereitete Billerbeck-Ergebnisse übernehmen (bis 75)</Button></div>{data.operations.aiConfigured&&<><Choice id="legacy-ai-region" label="Gebiet für API-Zusammenfassungen" value={analysisRegion} onChange={setAnalysisRegion} items={populated.map(s=>({id:s.id,name:s.name}))}/><Button disabled={busy||analysisRegion==='all'} onClick={()=>startAnalysis('summaries')}>API-Zusammenfassungen erstellen (bis 8)</Button></>}</details>
  </section>
  <footer className="admin-footer">Kennzahlen aus der aktuellen Datenbank. Artikelzahlen schließen zusammengeführte Verweise aus. <a href="/">Zur öffentlichen Website</a></footer>
 </main></div>;
}
