'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {RefreshCw,Download,ArrowUpRight,ShieldCheck,AlertCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {filterAdminSources,SOURCE_FILTERS,REVIEW_FILTERS} from '@/shared/admin.mjs';
import {regionName} from '@/shared/regions';
import {STATUS} from '@/shared/types';
import type {AdminDashboard,AdminSource} from '@/shared/admin-types';
const n=(v:number)=>v.toLocaleString('de-DE');
const date=(s:string|null)=>s?new Date(s).toLocaleString('de-DE',{timeZone:'Europe/Berlin',dateStyle:'short',timeStyle:'short'}):'Noch kein Abruf';
const pct=(a:number,b:number)=>b?(100*a/b).toLocaleString('de-DE',{maximumFractionDigits:1})+' %':'—';
function Choice({id,label,value,onChange,items}:{id:string;label:string;value:string;onChange:(value:string)=>void;items:{id:string;name:string}[]}){return <div className="admin-field"><label id={id+'-label'}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger aria-labelledby={id+'-label'}><SelectValue/></SelectTrigger><SelectContent position="popper">{items.map(item=><SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div>}
export function AdminDashboardView({initial,displayName,signOutPath}:{initial:AdminDashboard;displayName:string;signOutPath:string}){
 const [data,setData]=useState(initial),[filter,setFilter]=useState('data'),[query,setQuery]=useState(''),[limit,setLimit]=useState(25),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[importing,setImporting]=useState('');
 const [issue,setIssue]=useState('labels'),[reviewRegion,setReviewRegion]=useState('all'),[review,setReview]=useState(initial.review),[reviewBusy,setReviewBusy]=useState(false),[reviewError,setReviewError]=useState('');
 const [analysisRegion,setAnalysisRegion]=useState('all'),[analysing,setAnalysing]=useState('');
 const firstReview=useRef(true);
 const rows=useMemo(()=>filterAdminSources(data.sources,filter,query) as AdminSource[],[data.sources,filter,query]);
 const populated=data.sources.filter(s=>s.count>0),partial=populated.filter(s=>s.partial),stale=populated.filter(s=>s.stale),configuredEmpty=data.sources.filter(s=>s.configured&&!s.count);
 useEffect(()=>setLimit(25),[filter,query]);
 useEffect(()=>{
  if(firstReview.current){firstReview.current=false;return;}
  const controller=new AbortController();setReviewBusy(true);setReviewError('');
  fetch('/api/admin/review?'+new URLSearchParams({issue,region:reviewRegion}),{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json() as AdminDashboard['review'] & {error?:string};if(!r.ok)throw Error(d.error||'Prüfliste nicht erreichbar.');return d;}).then(setReview).catch(e=>{if(e.name!=='AbortError')setReviewError(e.message);}).finally(()=>{if(!controller.signal.aborted)setReviewBusy(false);});
  return ()=>controller.abort();
 },[issue,reviewRegion,data.asOf]);
 async function refresh(preserveError=false){setRefreshing(true);if(!preserveError)setError('');try{const r=await fetch('/api/admin/overview',{cache:'no-store'}),d=await r.json() as AdminDashboard & {error?:string};if(!r.ok)throw Error(d.error||'Aktualisierung fehlgeschlagen.');setData(d);}catch(e){setError(e instanceof Error?e.message:'Aktualisierung fehlgeschlagen.');}finally{setRefreshing(false);}}
 async function importSource(source:AdminSource){
  setImporting(source.id);setMessage('');setError('');
  try{const r=await fetch('/api/admin/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({region:source.id}),signal:AbortSignal.timeout(160000)}),d=await r.json() as {error?:string;topics?:number;coverage?:{complete?:boolean}};if(!r.ok)throw Error(d.error||'Import fehlgeschlagen.');setMessage(source.name+': '+n(d.topics||0)+' Einträge abgerufen. '+(d.coverage?.complete?'Keine technische Lücke gemeldet.':'Teilstand – bitte die Quellenhinweise prüfen.'));}catch(e){setError(e instanceof Error&&e.name!=='TimeoutError'?e.message:'Der Abruf dauert länger. Bitte den Importverlauf aktualisieren, bevor du erneut startest.');}finally{setImporting('');await refresh(true);}
 }
 async function startAnalysis(mode:'analysis'|'summaries'){
  setAnalysing(mode);setMessage('');setError('');
  try{const r=await fetch('/api/admin/analyse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({region:analysisRegion,mode}),signal:AbortSignal.timeout(160000)}),d=await r.json() as {error?:string;processed?:number;remaining?:number;more?:boolean};if(!r.ok)throw Error(d.error||'Analyse fehlgeschlagen.');setMessage(mode==='analysis'?n(d.processed||0)+' Artikel analysiert. '+n(d.remaining||0)+' stehen in dieser Auswahl noch aus. Ein weiterer Lauf startet erst mit deinem nächsten Klick.':n(d.processed||0)+' Artikel zur Textverarbeitung übernommen. Ergebnisse und Hinweise stehen im Importverlauf.');}catch(e){setError(e instanceof Error&&e.name!=='TimeoutError'?e.message:'Die Antwort dauert länger. Bitte zuerst den Verlauf aktualisieren; es wird kein weiterer Lauf automatisch gestartet.');}finally{setAnalysing('');await refresh(true);}
 }
 async function importPrepared(){
  setAnalysing('prepared');setError('');setMessage('');
  try{const r=await fetch('/api/admin/prepared-analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}),d=await r.json() as {error?:string;processed:number;skipped:number;remaining:number;conflicts:number};if(!r.ok)throw Error(d.error||'Übernahme fehlgeschlagen.');setMessage(n(d.processed)+' Billerbeck-Ergebnisse gespeichert · '+n(d.skipped)+' bereits vorhanden · '+n(d.remaining)+' noch ausstehend · '+n(d.conflicts)+' Abweichungen zum vorbereiteten Datenstand. Jeder weitere Lauf benötigt einen Klick.');}catch(e){setError(e instanceof Error?e.message:'Übernahme fehlgeschlagen.');}finally{setAnalysing('');await refresh(true);}
 }
 const pendingAnalysis=analysisRegion==='all'?data.counts.pendingAnalysis:data.sources.find(s=>s.id===analysisRegion)?.pendingAnalysis||0;
 const busy=!!importing||!!analysing||!!data.importBusyUntil;
 function sourceFocus(next:string){setFilter(next);setQuery('');}
 return <main id="inhalt" className="admin-shell">
  <header className="admin-topbar"><a className="wordmark" href="/">vor Ort<span className="wordmark__dot">.</span></a><span className="admin-access"><ShieldCheck size={16}/> Administration</span><a target="_top" href={signOutPath}>Abmelden</a></header>
  <div className="admin-heading"><div><p className="eyebrow">BESTAND & BETRIEB</p><h1>Alles im Blick.</h1><p>{displayName} · Datenbankstand {date(data.asOf)} Uhr</p></div><Button className="admin-refresh" variant="outline" onClick={()=>refresh()} disabled={refreshing||!!importing||!!analysing}><RefreshCw size={16} className={refreshing?'admin-spin':''}/>{refreshing?'Wird geladen …':'Zahlen aktualisieren'}</Button></div>
  {error&&<p className="admin-error" role="alert">{error} Der letzte geladene Stand bleibt sichtbar.</p>}
  {message&&<p role="status" className="admin-notice">{message}</p>}
  <section className="admin-kpis" aria-label="Bestandskennzahlen">
   <div className="admin-kpi admin-kpi-primary"><span>Artikel online</span><strong>{n(data.counts.online)}</strong><small>Eigenständige Vorgänge im Themenfeed</small></div>
   <a className="admin-kpi" href="#admin-quellen" onClick={()=>sourceFocus('data')}><span>Gebiete mit Artikeln</span><strong>{n(populated.length)}<em> / {data.sources.length}</em></strong><small>{populated.filter(s=>s.kind==='city').length} Kommunen · {populated.filter(s=>s.kind==='district').length} Kreise</small></a>
   <a className="admin-kpi" href="#admin-quellen" onClick={()=>sourceFocus('partial')}><span>Quellen mit Teilstand</span><strong>{n(partial.length)}</strong><small>Unter den Gebieten mit Artikeln</small></a>
   <a className="admin-kpi" href="#admin-qualitaet" onClick={()=>{setIssue('labels');setReviewRegion('all');}}><span>Label noch offen</span><strong>{pct(data.counts.unlabelled,data.counts.online)}</strong><small>{n(data.counts.unlabelled)} Artikel zur Einordnung</small></a>
  </section>
  <nav className="admin-nav" aria-label="Bereiche der Administration"><a href="#admin-analyse">Analyse starten</a><a href="#admin-quellen">Quellen</a><a href="#admin-qualitaet">Inhaltsqualität</a><a href="#admin-importe">Importverlauf</a><a href="#admin-betrieb">Betrieb</a><a href="/" target="_blank" rel="noreferrer">Website ansehen <ArrowUpRight size={15}/></a></nav>
  <div className="admin-attention"><AlertCircle size={19}/><div><strong>Als Nächstes prüfen</strong><p><a href="#admin-quellen" onClick={()=>sourceFocus('partial')}>{partial.length} Quellen mit Lücken</a> · <a href="#admin-quellen" onClick={()=>sourceFocus('stale')}>{stale.length} ältere Datenstände</a> · <a href="#admin-quellen" onClick={()=>sourceFocus('empty')}>{configuredEmpty.length} konfigurierte Quellen ohne Artikel</a></p></div></div>
  <section id="admin-quellen" className="admin-section">
   <div className="admin-section-heading"><div><p className="eyebrow">01 / QUELLEN</p><h2>Wo kommen die Daten an?</h2></div><a className="admin-download" href={'/api/admin/export?'+new URLSearchParams({filter,q:query})}><Download size={16}/> Auswahl als CSV</a></div>
   <div className="admin-source-controls"><div className="admin-field"><label htmlFor="admin-source-search">Ort oder Gemeindeschlüssel</label><Input id="admin-source-search" type="search" placeholder="Zum Beispiel Billerbeck" value={query} maxLength={120} onChange={e=>setQuery(e.target.value)}/></div><Choice id="admin-source-state" label="Datenzustand" value={filter} onChange={setFilter} items={SOURCE_FILTERS}/></div>
   <p className="admin-note">{rows.length} passende Gebiete. „Älter“ bedeutet: seit mindestens sieben Tagen keine Datenübernahme. Eine fehlerfreie Übernahme ist keine Vollständigkeitsgarantie.</p>
   {(importing||data.importBusyUntil)&&<p role="status" className="admin-notice">{importing?'Import von '+regionName(importing)+' läuft. Das kann etwa zwei Minuten dauern. Bitte diese Seite geöffnet lassen.':'Ein Import ist gesperrt oder läuft bereits. Sperre längstens bis '+date(data.importBusyUntil)+' Uhr. Bitte anschließend die Zahlen aktualisieren.'}</p>}
   <Table className="admin-table"><TableHeader><TableRow><TableHead>Gebiet</TableHead><TableHead className="admin-number">Artikel</TableHead><TableHead>Zustand & Datenstand</TableHead><TableHead>Prüfen / aktualisieren</TableHead></TableRow></TableHeader><TableBody>{rows.slice(0,limit).map(s=><TableRow key={s.id}><TableCell><a className="admin-strong" href={'/?region='+s.id}>{s.name}</a><small>{s.kind==='city'?'Kommune':'Kreis'} · {s.method==='oparl'?'OParl':s.method==='official-api'?'Portal-API':s.method==='scraper'?'Öffentliche RIS-Seiten':'Keine Quelle'}</small></TableCell><TableCell className="admin-number">{n(s.count)}</TableCell><TableCell><span className={'admin-state'+(s.attention?' needs-attention':'')}>{s.state}</span>{s.stale&&s.partial&&<small>Datenstand älter als sieben Tage</small>}<small>{date(s.lastSuccessAt)}{s.lastSuccessAt?' Uhr':''}</small>{s.issues.length>0&&<details className="admin-source-issues"><summary>{s.issues.length} Quellenhinweise</summary><ul>{s.issues.map((v,i)=><li key={i}>{v}</li>)}</ul><p>Letzter Versuch: {date(s.lastAttemptAt)}{s.nextRetryAt&&<> · Geplanter Wiederholungsversuch frühestens {date(s.nextRetryAt)}</>}</p></details>}</TableCell><TableCell><div className="admin-row-actions"><a href={'/quellen?region='+s.id}>Quellenansicht <ArrowUpRight size={14}/></a>{s.canImport&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>importSource(s)}>{importing===s.id?'Läuft …':'Neu einlesen'}</Button>}</div></TableCell></TableRow>)}</TableBody></Table>
   {!rows.length&&<p className="admin-empty">Für diese Auswahl wurden keine Gebiete gefunden.</p>}{rows.length>limit&&<Button variant="outline" onClick={()=>setLimit(v=>v+25)}>Weitere 25 Gebiete anzeigen</Button>}
   <p className="admin-note">„Neu einlesen“ startet einen einzelnen Quellenabruf. Vorhandene Artikel bleiben erhalten. Die Analyse neuer Artikel muss separat gestartet werden. Neue Entscheidungen in Münster können die bestehende Push-Benachrichtigung auslösen.</p>
  </section>
  <section id="admin-analyse" className="admin-section">
   <div className="admin-section-heading"><div><p className="eyebrow">MANUELLER START</p><h2>Neue Artikel analysieren</h2></div></div>
   <p>Seitenaufrufe und Quellenimporte erzeugen keine neuen Labels, Themenmerkmale oder KI-Zusammenfassungen. Bereits gespeicherte Ergebnisse bleiben verfügbar.</p>
   <div className="admin-source-controls"><Choice id="admin-analysis-region" label="Gebiet für die Analyse" value={analysisRegion} onChange={setAnalysisRegion} items={[{id:'all',name:'Alle Gebiete mit Artikeln'},...populated.map(s=>({id:s.id,name:s.name}))]}/><div><strong>{n(pendingAnalysis)} Artikel ausstehend</strong><p className="admin-note">Fehlende oder veraltete Labels bzw. Vergleichsmerkmale. Ein bereits geprüftes, mehrdeutiges Label wird nicht erneut bearbeitet.</p></div></div>
   <Button disabled={busy||pendingAnalysis===0} onClick={()=>startAnalysis('analysis')}>{analysing==='analysis'?'Analyse läuft …':'Labels & Themenmerkmale erstellen (bis 500)'}</Button>
   <p className="admin-note">Regelbasiert aus dem Originaltitel. Genau ein Paket je Klick; keine automatische Fortsetzung und keine KI-Anfrage. Bestehende Labels können vorhanden sein, auch wenn Vergleichsmerkmale noch fehlen.</p>
   <div className="admin-explainer"><h3>Billerbeck: vorbereitete Inhaltsanalyse</h3><p>402 geprüfte Quellenzuordnungen: 310 KI-Zusammenfassungen und 92 Fälle ohne ausreichenden Sachtext. Die Texte wurden durch Codex erstellt, nicht unabhängig fachlich freigegeben. Diese Schaltfläche übernimmt das feste Testpaket ohne externe KI-Anfrage.</p><Button variant="outline" disabled={busy} onClick={importPrepared}>{analysing==='prepared'?'Wird gespeichert …':'Testergebnisse übernehmen (bis 75)'}</Button><p className="admin-note">Bereits übernommene Ergebnisse werden übersprungen. Geänderte Quelldaten werden als Konflikt gemeldet und nicht überschrieben.</p></div>
   {data.operations.aiConfigured&&<><Button variant="outline" disabled={busy||analysisRegion==='all'} onClick={()=>startAnalysis('summaries')}>{analysing==='summaries'?'Textverarbeitung läuft …':'KI-Zusammenfassungen erstellen (bis 8)'}</Button><p className="admin-note">Separater, gegebenenfalls kostenpflichtiger API-Aufruf. Bitte dafür ein einzelnes Gebiet wählen. Startet ausschließlich durch diesen Klick.</p></>}
  </section>
  <section id="admin-qualitaet" className="admin-section">
   <div className="admin-section-heading"><div><p className="eyebrow">02 / INHALTSQUALITÄT</p><h2>Was braucht einen zweiten Blick?</h2></div></div>
   <div className="admin-quality-stats"><div><strong>{n(data.counts.aiSummaries)}</strong><span>KI-Zusammenfassungen</span></div><div><strong>{n(data.counts.online-data.counts.aiSummaries)}</strong><span>Ohne aktuelle KI-Kennzeichnung</span></div><div><strong>{n(data.counts.pdfArticles)}</strong><span>Artikel mit PDF-Verweis</span></div><div><strong>{n(data.counts.qualityPassed)}</strong><span>Technische Textprüfung bestanden</span></div></div>
   <div className="admin-quality-stats"><div><strong>{n(data.counts.contentSummaries)}</strong><span>Inhaltsanalysen abgeschlossen</span></div><div><strong>{n(data.counts.summaryInsufficient)}</strong><span>Sachtext unzureichend</span></div><div><strong>{n(data.counts.summaryStale)}</strong><span>Inhaltsanalyse veraltet</span></div><div><strong>{n(data.counts.aiLabels)}</strong><span>Separate KI-Labels</span></div><div><strong>{n(data.counts.weightedKeywords)}</strong><span>Gewichtete Stichwortprofile</span></div></div>
   <p className="admin-note">Technische Prüfungen ersetzen keine unabhängige fachliche Bewertung. Die Labelstatistik zeigt die regelbasierte Einordnung; KI-Labels aus dem Billerbeck-Test werden separat gespeichert und auf den Artikelseiten gegenübergestellt. Frühere Vergleichsstudien bleiben eigenständige Auswertungen.</p>
   <div className="admin-charts"><div><h3>Thematische Einordnung</h3>{data.labels.filter(l=>l.count>0).sort((a,b)=>b.count-a.count).map(l=><div className="admin-bar-row" key={l.id}><div><span>{l.name}</span><span>{n(l.count)} · {pct(l.count,data.counts.online)}</span></div><div className="admin-bar" aria-hidden="true"><span style={{width:(data.counts.online?100*l.count/data.counts.online:0)+'%'}}/></div></div>)}</div><div><h3>Verfahrensstand</h3>{data.statuses.map(s=><div className="admin-status-row" key={s.id}><span>{STATUS[s.id as keyof typeof STATUS]?.label||'Unbekannt'}</span><strong>{n(s.count)}</strong></div>)}<div className="admin-explainer"><strong>{n(data.counts.updated7d)} Artikel in sieben Tagen aktualisiert</strong><p>Gezählt nach dem gespeicherten Aktualisierungsdatum. Eine neue Übernahme kann auch bereits vorhandene Artikel aktualisieren; dies ist keine Zahl neu entstandener Themen.</p></div></div></div>
   <div className="admin-review-head"><h3>Prüfliste</h3><p>Bis zu 25 zuletzt aktualisierte Treffer. Die Links öffnen den Artikel zur Prüfung.</p></div>
   <div className="admin-source-controls"><Choice id="admin-review-issue" label="Prüfgrund" value={issue} onChange={setIssue} items={REVIEW_FILTERS}/><Choice id="admin-review-region" label="Gebiet" value={reviewRegion} onChange={setReviewRegion} items={[{id:'all',name:'Alle Gebiete mit Artikeln'},...populated.map(s=>({id:s.id,name:s.name}))]}/></div>
   {reviewError?<p role="alert" className="admin-error">{reviewError}</p>:reviewBusy?<p role="status" className="admin-empty">Prüfliste wird geladen …</p>:<><p className="admin-note">{n(review.total)} Artikel passen zu dieser Auswahl.</p><ol className="admin-review-list">{review.articles.map(a=><li key={a.id}><div><a href={'/thema/'+a.id} target="_blank" rel="noreferrer">{a.title} <ArrowUpRight size={15}/></a><small>{regionName(a.regionId)} · Aktualisiert {date(a.updatedAt)}</small></div></li>)}</ol>{!review.articles.length&&<p className="admin-empty">Keine Treffer für diesen Prüfgrund.</p>}</>}
  </section>
  <section id="admin-importe" className="admin-section"><p className="eyebrow">03 / IMPORTVERLAUF</p><h2>Die letzten Abrufe</h2><p className="admin-note">Hier erscheinen die letzten 30 im Backend gestarteten Läufe. Extern eingespielte Nachladungen sind über den Quellenstand dokumentiert.</p>
   {!data.runs.length?<p className="admin-empty">Noch keine Backend-Importläufe protokolliert. Über „Neu einlesen“ kannst du eine konfigurierte Quelle aktualisieren.</p>:<Table className="admin-table"><TableHeader><TableRow><TableHead>Beginn</TableHead><TableHead>Gebiet / Auslöser</TableHead><TableHead>Ergebnis</TableHead><TableHead className="admin-number">Einträge</TableHead></TableRow></TableHeader><TableBody>{data.runs.map(r=><TableRow key={r.id}><TableCell>{date(r.startedAt)}<small>{r.mode==='prepared-analysis'?'Vorbereiteter KI-Test':r.mode==='summaries'?'Textverarbeitung':r.mode==='analysis'?'Labels & Themenmerkmale':'Quellenimport'}</small></TableCell><TableCell>{r.region==='all'?'Alle Gebiete':regionName(r.region)}<small>{r.trigger==='scheduled'?'Geplant':r.trigger==='manual'?'Manuell':'Auslöser nicht erfasst'}</small></TableCell><TableCell><span className={'admin-state'+(['failed','partial'].includes(r.status)||r.abandoned?' needs-attention':'')}>{r.abandoned?'Status offen: länger als 10 Minuten':({completed:'Abgeschlossen',partial:'Teilweise übernommen',failed:'Fehlgeschlagen',running:'Läuft'}[r.status]||r.status)}</span>{r.finishedAt&&<small>Ende {date(r.finishedAt)}</small>}{r.issueCount>0&&<small>{r.issueCount} Hinweise im Quellenstand</small>}</TableCell><TableCell className="admin-number">{r.count===null?'—':n(r.count)}</TableCell></TableRow>)}</TableBody></Table>}
  </section>
  <section id="admin-betrieb" className="admin-section"><p className="eyebrow">04 / BETRIEB</p><h2>Was ist eingerichtet?</h2><dl className="admin-operations"><div><dt>Datenbank</dt><dd>Erreichbar · {n(data.counts.versions)} archivierte Fassungen · {n(data.counts.analysisVersions)} Analysefassungen · {n(data.counts.aliases)} zusammengeführte Verweise</dd></div><div><dt>Automatische Importe</dt><dd>{data.lastScheduledAt?'Letzter protokollierter geplanter Start: '+date(data.lastScheduledAt):'Kein geplanter Lauf protokolliert'}<small>Ein manueller Abruf aktiviert keinen Zeitplan. Ein früherer Lauf bestätigt keine dauerhaft aktive Planung.</small></dd></div><div><dt>Laufende KI-Zusammenfassungen</dt><dd>{data.operations.aiConfigured?'API-Zugang eingerichtet':'API-Zugang nicht eingerichtet'}<small>Nur ein ausdrücklicher Start über die separate Schaltfläche verarbeitet neue Texte.</small></dd></div><div><dt>Push für Münster</dt><dd>{data.operations.pushConfigured?'Versand konfiguriert':'Versand nicht konfiguriert'} · {n(data.counts.pushSubscriptions)} gespeicherte Abonnements<small>Ein gespeichertes Abonnement ist kein Nachweis einer zugestellten Nachricht.</small></dd></div><div><dt>Besucherzahlen</dt><dd>Werden bisher nicht erfasst.</dd></div></dl></section>
  <footer className="admin-footer">Kennzahlen aus der aktuellen Datenbank. Artikelzahlen schließen zusammengeführte Verweise aus. <a href="/">Zur öffentlichen Website</a></footer>
 </main>;
}
