'use client';
import {useEffect,useRef,useState} from 'react';
import {Download,RefreshCw,Play,Pause,Check,Database,MapPinned,Globe} from 'lucide-react';
import {AdminHeader} from '@/components/admin-chrome';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AdminProcessingMap} from '@/components/admin-processing-map';
import {splitAiResultBatches} from '@/shared/ai-result-batches.mjs';
import {HISTORY_WINDOWS} from '@/shared/history-window.mjs';
import {ALL_LANDS} from '@/shared/lands.mjs';
import {mergeJob} from '@/shared/pipeline-job.mjs';
import {DatabaseAdmin} from '@/components/database-admin';
import {AdminTimeline} from '@/components/admin-timeline';
import {AdminRunDebug} from '@/components/admin-run-debug';
import type {AdminDashboard,AdminSource,PipelineJob} from '@/shared/admin-types';
const n=(v:number)=>v.toLocaleString('de-DE');
const date=(s:string|null|undefined)=>s?new Date(s).toLocaleString('de-DE',{timeZone:'Europe/Berlin',dateStyle:'short',timeStyle:'short'}):'Noch nicht erfasst';
const kindNames:Record<string,string>={summary:'KI-Zusammenfassung',aiLabel:'KI-Label aus Inhalt',keywords:'Gewichtete Stichwörter'};
const stateNames:Record<string,string>={queued:'Ausstehend',running:'Läuft',completed:'Gespeichert',partial:'Teilstand gespeichert',failed:'Fehlgeschlagen',unavailable:'Keine Quelle',unknown:'Ausgang prüfen',cancelled:'Beendet'};
// Look-back windows for stage 01; the same keys are validated on the server.
const windowItems=Object.entries(HISTORY_WINDOWS).map(([id,w])=>[id,w.label]) as [string,string][];
const windowLabel=(id?:string)=>windowItems.find(([key])=>key===id)?.[1]||'';
// A browser opens six connections to one server. The page uses four of them for requests that each run six imports
// side by side on the server (24 at once, the server's own limit) and keeps two free for status, pause and overview.
const RUNNERS:Record<string,{requests:number;lanes:number}>={metadata:{requests:4,lanes:6},analysis:{requests:1,lanes:1}};
// Order of the areas in the result list of a job: what needs attention comes first. The list shows this many rows.
const JOB_ORDER=['running','failed','unknown','partial','queued','completed','unavailable'],JOB_ROWS=60;
function Choice({label,value,onChange,items}:{label:string;value:string;onChange:(s:string)=>void;items:[string,string][]}){return <label className="admin-field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,name])=><SelectItem key={v} value={v}>{name}</SelectItem>)}</SelectContent></Select></label>;}
async function api(url:string,body?:unknown):Promise<any>{const r=await fetch(url,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{} )}),data=await r.json() as any;if(!r.ok)throw Error(data.error||'Anfrage fehlgeschlagen.');return data;}
function download(data:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
// initialSelection: areas handed over by the estimate page ("/admin?auswahl=…") as candidates for a twelve-month import.
export function AdminProcessing({initial,displayName,signOutPath,initialSelection=[]}:{initial:AdminDashboard;displayName:string;signOutPath:string;initialSelection?:string[]}){
 const [data,setData]=useState(initial),[selected,setSelected]=useState<Set<string>>(new Set(initialSelection.length?initialSelection:['billerbeck'])),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[layer,setLayer]=useState('city'),[mode,setMode]=useState('coverage'),[page,setPage]=useState(1);
 const [busy,setBusy]=useState(''),[running,setRunning]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(initialSelection.length?`${initialSelection.length} Gebiete aus der Hochrechnung ausgewählt. Für ein vollständiges Jahr ist in Stufe 01 der Zeitraum „12 Monate“ eingestellt; der Abruf startet erst mit „Auswahl aktualisieren“.`:''),[job,setJob]=useState(initial.processing.job),[kinds,setKinds]=useState(['summary','aiLabel','keywords']),[batchSize,setBatchSize]=useState('10'),[retryBlocked,setRetryBlocked]=useState(false);
 const [lookback,setLookback]=useState(initialSelection.length?'12m':'1m'),[land,setLand]=useState('all'),[jobFilter,setJobFilter]=useState('all');
 const [local,setLocal]=useState(false);useEffect(()=>setLocal(['localhost','127.0.0.1','[::1]'].includes(window.location.hostname)),[]);
 const pause=useRef(false),file=useRef<HTMLInputElement>(null);
 const chosen=data.sources.filter(s=>selected.has(s.id)),total=chosen.reduce((a,s)=>a+s.count,0),count=(key:string)=>chosen.reduce((a,s)=>a+Number(s.processing[key as keyof typeof s.processing]||0),0);
 const visible=data.sources.filter(s=>s.kind===layer&&(land==='all'||s.land===land)&&(!query||[s.name,s.ags].join(' ').toLocaleLowerCase('de-DE').includes(query.toLocaleLowerCase('de-DE')))&&(filter==='all'||filter==='data'&&s.count>0||filter==='issues'&&(s.attention||s.issues.length>0)||filter==='selected'&&selected.has(s.id)));
 const toggle=(id:string)=>setSelected(prev=>{const next=new Set(prev);if(next.has(id))next.delete(id);else next.add(id);return next;});
 const busySource=busy!==''||running||!!data.importBusyUntil;
 async function refresh(){const next:AdminDashboard=await api('/api/admin/overview?review=0');setData(next);setJob(next.processing.job);return next;}
 async function action(name:string,fn:()=>Promise<void>){setBusy(name);setError('');setMessage('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Aktion fehlgeschlagen.');}finally{setBusy('');}}
 async function drain(start:PipelineJob){
  pause.current=false;setRunning(true);
  const runner=RUNNERS[start.stage]||RUNNERS.analysis;
  let latest=start,stopped=false,reloading=false,reloaded=Date.now(),rest=60000;
  // Replies of parallel requests can arrive out of order, and most list only the areas changed since the state the
  // page named; mergeJob keeps the newest state of every area and of the job.
  const show=(next:PipelineJob)=>{latest=mergeJob(latest,next) as PipelineJob;setJob(latest);};
  const call=(action:string,extra:Record<string,unknown>={}):Promise<PipelineJob>=>api('/api/admin/pipeline',{action,id:start.id,since:latest.updatedAt,...extra});
  const open=()=>!pause.current&&!['completed','cancelled'].includes(latest.status);
  // The overview reads every stored report and keeps the database busy meanwhile, so the running steps and every
  // other page wait for it. Beside a job it is reloaded at most once a minute and takes at most a tenth of the time;
  // the progress of the job itself comes with the answers of the steps.
  const reload=()=>{if(reloading||Date.now()-reloaded<rest)return;reloading=true;const began=Date.now();void api('/api/admin/overview?review=0').then((next:AdminDashboard)=>setData(next)).catch(()=>{}).finally(()=>{reloading=false;reloaded=Date.now();rest=Math.max(60000,10*(reloaded-began));});};
  // One request runs several imports side by side on the server and returns when they are stored.
  const worker=async()=>{try{while(open()){
   const next=await call('run',{lanes:runner.lanes});show(next);
   // The server pauses a job itself when another process holds the stock.
   if(next.paused)pause.current=true;
   else if(next.wait)await new Promise(done=>setTimeout(done,2500));
   reload();
  }}catch(e){pause.current=true;throw e;}};
  // Between the answers of those requests the progress is asked for.
  const watch=async()=>{while(!stopped){await new Promise(done=>setTimeout(done,4000));if(stopped)break;try{show(await call('status'));}catch{}}};
  try{
   // A job paused earlier (by the operator or by the server) takes areas again from here on.
   show(await call('resume'));void watch();
   const outcomes=await Promise.allSettled(Array.from({length:runner.requests},worker));
   stopped=true;
   const conflict=latest.items.some(i=>i.status==='queued'&&i.message?.includes('läuft bereits'));
   await refresh();
   const failed=outcomes.find(o=>o.status==='rejected');if(failed)throw (failed as PromiseRejectedResult).reason;
   if(conflict)setMessage('Andere Verarbeitung läuft. Später ausdrücklich fortsetzen.');else if(!pause.current)setMessage('Auftrag beendet. Teilstände und Fehler stehen im Verlauf unten.');
  }finally{stopped=true;setRunning(false);}
 }
 const activeJob=job&&!['completed','cancelled'].includes(job.status);
 // scope 'sources': every area with a connected source in all states, whatever is selected on the page.
 // The start for all of Germany ends an open job (replace); its label says so beforehand.
 async function start(stage:string,scope?:'sources'){await action(scope||stage,async()=>{const next=await api('/api/admin/pipeline',{action:'create',stage,regions:scope||[...selected],...(stage==='metadata'?{window:lookback}:{}),...(scope&&activeJob?{replace:true}:{})});setJob(next);await drain(next);});}
 const connected=data.sources.filter(s=>s.canImport).length;
 // Per state: areas, areas with a connected source, areas with stored reports.
 const byLand=ALL_LANDS.map(l=>{const own=data.sources.filter(s=>s.land===l.id);return {...l,areas:own.length,connected:own.filter(s=>s.canImport).length,stocked:own.filter(s=>s.count>0).length};});
 const openAreas=job?job.items.filter(i=>i.status==='queued'||i.status==='running').length:0;
 const jobCounts:Record<string,number>={};for(const i of job?.items||[])jobCounts[i.status]=(jobCounts[i.status]||0)+1;
 const jobDone=(job?.items.length||0)-(jobCounts.queued||0)-(jobCounts.running||0),jobShown=jobFilter!=='all'&&!jobCounts[jobFilter]?'all':jobFilter;
 const jobRows=job?job.items.filter(i=>jobShown==='all'||i.status===jobShown).sort((a,b)=>JOB_ORDER.indexOf(a.status)-JOB_ORDER.indexOf(b.status)):[];

 async function downloadAi(id:string){
  let combined:any=null,offset=0;
  do{
   const part=await api('/api/admin/ai-job?id='+encodeURIComponent(id)+'&offset='+offset);
   if(!part||part.id!==id||!Array.isArray(part.articles))throw Error('Auftrag konnte nicht geladen werden.');
   if(!combined)combined={...part,articles:[]};
   if(!part.articles.length&&offset<part.articleCount)throw Error('Auftrag ist unvollständig. Bitte erneut herunterladen.');
   combined.articles.push(...part.articles);offset=combined.articles.length;
   setMessage(`${n(offset)} / ${n(part.articleCount??offset)} Auftragsartikel geladen …`);
  }while(offset<(combined.articleCount??offset));
  download(combined,'ratsmonitor-ki-auftrag-'+id+'.json');
 }
 async function makeAi(){await action('ai',async()=>{
  const next=await api('/api/admin/ai-job',{action:'create',regions:[...selected],kinds,limit:batchSize==='all'?'all':Number(batchSize),retryBlocked});
  try{
   if(next.articleCount)await downloadAi(next.id);
   const held=next.blocked?` ${n(next.blocked)} Artikel ohne erneuten Versuch, weil ihre Quelle nicht ausreichte und sich seitdem nicht geändert hat.`:'';
   setMessage(next.articleCount?`${n(next.articleCount)} Artikel mit ${n(next.requestedSteps??next.articleCount)} fehlenden Einzelschritten reserviert.${next.sharedSources?.length?` ${n(next.sharedSources.length)} Quellen nutzen mehrere Artikel gemeinsam; der Agent liest sie nur einmal.`:''}${next.quickChecks?` ${n(next.quickChecks)} Artikel ohne Vorlage oder Anlage erhalten nur eine Schnellprüfung.`:''} Auftrag speichern und den KI-Agenten deiner Wahl manuell damit starten. Teilergebnisse können nacheinander eingelesen werden.${held}`:`In der Auswahl stehen für diese KI-Schritte keine Artikel aus.${held}`);
  }finally{await refresh();}
 });}
 async function importAi(f:File){await action('ai-import',async()=>{
  if(f.size>100000000)throw Error('Datei größer als 100 MB. Ergebnisse in mehrere Dateien mit derselben jobId aufteilen.');
  const batches=splitAiResultBatches(JSON.parse(await f.text()));
  let applied=0,skipped=0,conflicts=0,ignored=0;
  try{
   for(let i=0;i<batches.length;i++){
    const receipt=await api('/api/admin/ai-job',{action:'apply',result:batches[i]});
    applied+=receipt.applied;skipped+=receipt.skipped;conflicts+=receipt.conflicts.length;ignored+=receipt.ignored||0;
    setMessage(`Paket ${i+1} / ${batches.length} geprüft · ${n(applied)} Artikel gespeichert · ${n(skipped)} bereits vorhanden · ${n(conflicts)} Konflikte.`);
   }
   setMessage(`${n(applied)} Artikel gespeichert und zurückgelesen · ${n(skipped)} bereits vorhanden · ${n(conflicts)} Konflikte.${ignored?` ${n(ignored)} nicht angeforderte Einzelergebnisse ignoriert.`:''} Noch nicht gelieferte Artikel bleiben reserviert.`);
  }catch(e){throw Error(`Übernahme unterbrochen: ${n(applied)} Artikel gespeichert, ${n(skipped)} bereits vorhanden, ${n(conflicts)} Konflikte. Dieselbe Datei kann erneut eingelesen werden. ${e instanceof Error?e.message:''}`);}
  finally{await refresh();}
 });}
 const restore=data.processing.restore,aiJob=data.processing.aiJob;
 return <div className="admin-app"><AdminHeader page={1} displayName={displayName} signOutPath={signOutPath}/><main id="inhalt" className="admin-shell admin-workspace">
  <div className="admin-heading"><div><p className="eyebrow">DATEN & VERARBEITUNG</p><h1>Projektsteuerung.</h1><p>{displayName} · Stand {date(data.asOf)}</p></div><Button variant="outline" disabled={!!busy||running} onClick={()=>action('refresh',async()=>{await refresh();})}><RefreshCw size={16}/> Status aktualisieren</Button></div>
  <div className="admin-kpis"><div className="admin-kpi admin-kpi-primary"><span>Berichte gespeichert</span><strong>{n(data.counts.online)}</strong><small>In der verbundenen Datenbank</small></div><div className="admin-kpi"><span>Gebiete mit Daten</span><strong>{data.sources.filter(s=>s.count>0).length} <em>/ {data.sources.length}</em></strong><small>{n(data.sources.filter(s=>s.kind==='city').length)} Gemeinden und Gemeindeverbände, {n(data.sources.filter(s=>s.kind==='district').length)} Kreise in {new Set(data.sources.map(s=>s.land)).size} Ländern · {n(connected)} mit angebundener Quelle</small></div><div className="admin-kpi"><span>Letzter Abruf fehlgeschlagen</span><strong>{data.sources.filter(s=>s.attemptStatus==='failed').length}</strong><small>Vorheriger Bestand bleibt erhalten</small></div><div className="admin-kpi"><span>Deine Auswahl</span><strong>{chosen.length}</strong><small>{n(total)} Berichte · {chosen.filter(s=>!s.canImport).length} ohne angebundene Quelle</small></div></div>
  {error&&<p role="alert" className="admin-error">{error}</p>}{message&&<p role="status" className="admin-notice">{message}</p>}
  <section className="admin-germany" aria-labelledby="ganz-deutschland"><div className="admin-germany-text"><p className="eyebrow">GANZ DEUTSCHLAND</p><h2 id="ganz-deutschland"><Globe size={22}/> Alle angebundenen Quellen abrufen</h2><p>{n(connected)} von {n(data.sources.length)} Gebieten haben eine angebundene Quelle. Der Abruf liest sie alle, unabhängig von der Auswahl unten: bis zu 24 Gebiete gleichzeitig, höchstens zwei auf demselben Server, die Server mit den meisten Gebieten zuerst.</p>
   <div className="admin-germany-lands" role="region" aria-label="Quellen je Land" tabIndex={0}><table><thead><tr><th>Land</th><th>Gebiete</th><th>Quelle angebunden</th><th>Mit Berichten</th></tr></thead><tbody>{byLand.map(l=><tr key={l.id} className={l.connected?undefined:'is-open'}><th>{l.name}</th><td>{n(l.areas)}</td><td>{n(l.connected)}</td><td>{n(l.stocked)}</td></tr>)}</tbody></table></div></div>
   <div className="admin-germany-action"><Choice label="Zeitraum rückwirkend" value={lookback} onChange={setLookback} items={windowItems}/><Button disabled={busySource||!connected} onClick={()=>start('metadata','sources')}><Play size={15}/> {activeJob?`Offenen Auftrag beenden und alle ${n(connected)} Quellen abrufen`:`Alle ${n(connected)} Quellen abrufen`}</Button>{activeJob&&!running&&<small>Der offene Auftrag ({job?.stage==='metadata'?'Abruf, '+windowLabel(job?.window):'Regel-Labeling'}, {n(openAreas)} Gebiete ausstehend) wird dabei beendet. Was er gespeichert hat, bleibt erhalten.</small>}{running&&<small>Ein Auftrag läuft gerade. Erst unten pausieren und warten, bis die laufenden Abrufe gespeichert sind.</small>}<small>Abgerufen werden Sitzungen ab {windowLabel(lookback)} zurück. Schließen der Seite pausiert den Abruf; „Auftrag fortsetzen“ macht dort weiter.</small></div></section>
  <section className="admin-territories"><div className="admin-section-heading"><h2><MapPinned size={22}/> Gebiete auswählen</h2><div className="admin-selection-actions"><Button variant="outline" disabled={running||land==='all'} onClick={()=>setSelected(new Set(data.sources.filter(s=>s.land===land).map(s=>s.id)))}>{land==='all'?'Bundesland wählen, um es ganz auszuwählen':'Ganz '+(ALL_LANDS.find(l=>l.id===land)?.short||'')+' auswählen'}</Button><Button variant="outline" disabled={running} onClick={()=>setSelected(new Set(data.sources.filter(s=>s.canImport&&(land==='all'||s.land===land)).map(s=>s.id)))}>Alle mit Quelle</Button><Button variant="outline" disabled={running} onClick={()=>setSelected(new Set(data.sources.filter(s=>s.count>0).map(s=>s.id)))}>Alle mit Daten</Button><Button variant="ghost" disabled={running} onClick={()=>setSelected(new Set())}>Auswahl leeren</Button></div></div>
  <div className="admin-geography"><div><div className="admin-source-controls"><Choice label="Bundesland" value={land} onChange={s=>{setLand(s);setPage(1);}} items={[["all","Alle Länder"],...ALL_LANDS.map(l=>[l.id,l.name] as [string,string])]}/><Choice label="Kartenebene" value={layer} onChange={s=>{setLayer(s);setPage(1);}} items={[["city","Städte & Gemeinden"],["district","Kreise"]]}/><Choice label="Kartenfarbe" value={mode} onChange={setMode} items={[["coverage","Datenabdeckung & Abruf"],["access","Zugang (OParl, API, HTML, Sperren)"],["count","Anzahl Berichte"],["rules","Anteil Regel-Labels"],["summary","Anteil KI-Zusammenfassungen"],["aiLabel","Anteil KI-Labels aus Inhalt"],["keywords","Anteil vollständiger Stichwortprofile"]]}/></div><AdminProcessingMap sources={data.sources} selected={selected} onToggle={toggle} layer={layer} mode={mode} land={land}/></div>
   <div className="admin-region-list"><div className="admin-source-controls"><label className="admin-field"><span>Ort oder Gemeindeschlüssel</span><Input value={query} placeholder="Billerbeck, Coesfeld …" onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><Choice label="Liste filtern" value={filter} onChange={s=>{setFilter(s);setPage(1);}} items={[["all","Alle Gebiete"],["data","Mit Daten"],["issues","Mit Hinweisen"],["selected","Ausgewählt"]]}/></div><div className="admin-list-meta"><span>{visible.length} Treffer · {chosen.length} ausgewählt</span><Button variant="link" onClick={()=>setSelected(prev=>new Set([...prev,...visible.map(s=>s.id)]))}>Alle Treffer auswählen</Button></div>
   <div className="admin-source-list">{visible.slice((page-1)*10,page*10).map(s=><div className={'admin-source-item'+(selected.has(s.id)?' is-selected':'')} key={s.id}><label><Checkbox checked={selected.has(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={s.name+' auswählen'}/><span><strong>{s.name}</strong><small>{s.accessLabel||(s.method==='oparl'?'OParl':s.method==='pending'?'Keine Quelle':'RIS')}{s.access==='api'&&s.channel?' ('+s.channel+')':''} · {s.state}</small></span><b>{n(s.count)}<small>Berichte</small></b></label><div className="admin-source-meta">Übernahme: {date(s.lastSuccessAt)}<br/>Letzter Versuch: {date(s.lastAttemptAt)}</div><details><summary>Verarbeitung & Quellenhinweise</summary><dl>{[['rules','Regel-Labels'],['summary','KI-Zusammenfassungen'],['aiLabel','KI-Labels'],['keywords','10 Inhaltsstichwörter']].map(([k,label])=><div key={k}><dt>{label}</dt><dd>{n(Number(s.processing[k as keyof typeof s.processing]||0))} / {n(s.count)}</dd></div>)}</dl><p>Letzte Bearbeitung: {date(s.processing.processedAt)}</p>{s.issues.length?<ul>{s.issues.map((issue,i)=><li key={i}>{issue}</li>)}</ul>:<p>Keine Abrufhinweise gespeichert. Das bestätigt keine vollständige Quelle.</p>}{s.warnings.length>0&&<><p><strong>Warnungen</strong> – sie machen den Abruf nicht unvollständig:</p><ul>{s.warnings.map((warning,i)=><li key={i}>{warning}</li>)}</ul></>}<a href={'/quellen?region='+s.id}>Quellen ansehen</a>{s.canImport&&<AdminRunDebug region={s.id} name={s.name}/>}</details></div>)}{!visible.length&&<p className="admin-empty">Keine passenden Gebiete.</p>}</div><div className="admin-list-meta"><Button variant="outline" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Zurück</Button><span>{page} / {Math.max(1,Math.ceil(visible.length/10))}</span><Button variant="outline" disabled={page*10>=visible.length} onClick={()=>setPage(p=>p+1)}>Weiter</Button></div></div></div>
  </section>
  <section className="admin-pipeline"><div className="admin-section-heading"><div><p className="eyebrow">FÜR DEINE AUSWAHL</p><h2>Vier Stufen. Jeder Start bewusst.</h2></div><span>{chosen.length} Gebiete · {n(total)} Berichte</span></div><p className="admin-note">Seitenaufrufe lesen nur den Status. Ein gestarteter Abrufauftrag liest bis zu 24 Gebiete gleichzeitig, höchstens zwei auf demselben Server, und beginnt bei den Servern mit den meisten Gebieten; Regel-Labeling läuft Gebiet für Gebiet. Beim Schließen der Seite stoppt die Fortsetzung nach den laufenden Schritten.</p>
   <div className="admin-stage-grid"><section className="admin-stage"><div className="admin-stage-number">01</div><h3>Amtliche Daten abrufen</h3><p>Öffentliche Vorgänge, Sitzungen, Gremien, dokumentierte Ergebnisse, Teilnehmerangaben und Originalverweise aus OParl oder RIS.</p><strong>{chosen.filter(s=>s.canImport).length} Quellen abrufbar</strong><small>{chosen.filter(s=>!s.canImport).length} ohne Anbindung werden als offen protokolliert.</small><Choice label="Zeitraum rückwirkend" value={lookback} onChange={setLookback} items={windowItems}/><small>Abgerufen werden Sitzungen ab {windowLabel(lookback)} zurück sowie bereits veröffentlichte Folgesitzungen. Ältere gespeicherte Berichte bleiben erhalten; ein längerer Zeitraum kann später nachgeladen werden.{["12m","24m"].includes(lookback)&&" Große Gebiete werden bei diesem Zeitraum in mehreren Teilen gelesen. Bleibt am Ende ein Teilstand, setzt ein neuer Auftrag mit demselben Zeitraum dort fort."}</small><Button disabled={busySource||!!activeJob||!chosen.length} onClick={()=>start('metadata')}><Play size={15}/> Auswahl aktualisieren</Button><small>Alle angebundenen Quellen in Deutschland ruft der Bereich „Ganz Deutschland“ oben ab.</small></section>
   <section className="admin-stage"><div className="admin-stage-number">02</div><h3>Regeln anwenden</h3><p>Regel-Labels und Vergleichsmerkmale aus den amtlichen Titeln. Unabhängig von der KI-Bewertung.</p><strong>{n(count('rules'))} / {n(total)} bearbeitet</strong><progress value={count('rules')} max={total||1}/><small>{n(total-count('rules'))} offen. Verarbeitung in Paketen von höchstens 500 Artikeln.</small><Button variant="outline" disabled={busySource||!!activeJob||!total||count('rules')===total} onClick={()=>start('analysis')}><Play size={15}/> Regel-Labeling starten</Button></section>
   <section className="admin-stage admin-stage-ai"><div className="admin-stage-number">03</div><h3>KI-Inhalte erarbeiten</h3><p>Der KI-Agent deiner Wahl liest die Originalinhalte. Du startest den heruntergeladenen Auftrag manuell in deinem Projekt.</p><div className="admin-ai-kinds">{Object.entries(kindNames).map(([k,label])=><label key={k}><Checkbox checked={kinds.includes(k)} onCheckedChange={checked=>setKinds(prev=>checked?[...prev,k]:prev.filter(x=>x!==k))}/><span>{label}<small>{n(count(k))} / {n(total)} aktuell gespeichert{count('blocked_'+k)>0&&` · ${n(count('blocked_'+k))} ohne ausreichende Quelle`}</small></span></label>)}</div><Choice label="Artikel je KI-Auftrag" value={batchSize} onChange={setBatchSize} items={[["10","10 · Testlauf"],["25","25 Artikel"],["50","50 Artikel"],["100","100 Artikel"],["all","Alle offenen Artikel"]]}/><label className="admin-ai-retry"><Checkbox checked={retryBlocked} onCheckedChange={checked=>setRetryBlocked(checked===true)}/><span>Artikel ohne ausreichende Quelle erneut versuchen<small>Nur sinnvoll, wenn sich am Agenten oder an der Quellenarbeit etwas geändert hat.</small></span></label><Button variant="outline" disabled={busySource||!total||!kinds.length||aiJob?.status==='prepared'} onClick={makeAi}><Download size={15}/> KI-Auftrag vorbereiten</Button><small>Gilt für die oben gewählten Gebiete und KI-Schritte. Je Artikel werden nur die noch fehlenden Schritte angefordert. Zuerst noch nicht exportierte Artikel, danach die am längsten zurückliegenden Exporte. Ein offener Auftrag reserviert seine Artikel bis zur Übernahme oder zum Verwerfen.</small><small>Reichte die Quelle für einen Schritt nicht, kommt der Artikel erst wieder, wenn sich seine Quelldaten ändern; nach einem technischen Fehler gibt es einen weiteren Versuch. Zehn Stichwörter, ganzzahlige Gewichte, Summe 100.</small></section>
   <section className="admin-stage"><div className="admin-stage-number">04</div><h3>Speicherung prüfen</h3><p>{local?'Du arbeitest mit dem lokalen Backend. Die gezeigten Bestände werden aus dessen Datenbank gelesen.':'Die Bestände stammen aus dem verbundenen Backend. Die Datenbank auf deinem Windows-PC ist von hier aus nicht einsehbar.'}</p><strong><Database size={17}/> Revision {n(data.processing.revision)}</strong><small>{n(total)} ausgewählte Berichte gespeichert. {n(count('summary'))} mit Inhaltszusammenfassung, {n(count('aiLabel'))} mit KI-Label und {n(count('keywords'))} mit zehn Inhaltsstichwörtern.</small><Button variant="outline" disabled={busySource} onClick={()=>action('verify',async()=>{await refresh();setMessage('Gespeicherte Bestände erneut aus der verbundenen Datenbank gelesen.');})}><Check size={16}/> Datenbankstand prüfen</Button><a href="#admin-datenbank">Export & Übernahme anzeigen</a></section></div>
  </section>
  {job&&<section className="admin-job"><div className="admin-section-heading"><div><h2>{job.stage==='metadata'?(job.scope==='sources'?'Abruf aller Quellen in Deutschland':'Abrufauftrag')+(job.window?' · '+windowLabel(job.window)+' rückwirkend':''):'Regel-Labeling'}</h2><p>{n(jobDone)} / {n(job.items.length)} Gebiete abgeschlossen · {running?`Läuft${jobCounts.running?' · '+jobCounts.running+' gleichzeitig':''}`:activeJob?'Pausiert – wartet auf deinen Start':'Beendet'}</p></div><div className="admin-selection-actions">{running?<Button variant="outline" onClick={()=>{pause.current=true;void api('/api/admin/pipeline',{action:'pause',id:job.id}).catch(()=>{});setMessage('Pause angefordert. Die laufenden Abrufe werden noch beendet und gespeichert.');}}><Pause size={16}/> Nach den laufenden Schritten pausieren</Button>:activeJob&&<><Button disabled={!!busy} onClick={()=>action('resume',()=>drain(job))}>Auftrag fortsetzen</Button><Button variant="outline" disabled={!!busy} onClick={()=>action('cancel',async()=>{setJob(await api('/api/admin/pipeline',{action:'cancel',id:job.id}));})}>Auftrag beenden</Button></>}</div></div>
   <progress className="admin-job-progress" value={jobDone} max={job.items.length||1} aria-label="Abgeschlossene Gebiete"/>
   <p className="admin-job-counts">{JOB_ORDER.filter(s=>jobCounts[s]).map(s=><span key={s}>{stateNames[s]||s}: <strong>{n(jobCounts[s])}</strong></span>)}<span>Berichte gelesen: <strong>{n(job.items.reduce((a,i)=>a+i.processed,0))}</strong></span></p>
   {/* Ein bundesweiter Auftrag hat mehrere tausend Gebiete: gezeigt wird ein Ausschnitt, Auffälliges zuerst. */}
   <details open={running}><summary>Ergebnisse je Gebiet</summary><div className="admin-source-controls"><Choice label="Anzeigen" value={jobShown} onChange={setJobFilter} items={[["all","Alle – Laufendes und Auffälliges zuerst"],...JOB_ORDER.filter(s=>jobCounts[s]).map(s=>[s,stateNames[s]||s] as [string,string])]}/></div><ul className="admin-job-results">{jobRows.slice(0,JOB_ROWS).map(i=>{const name=data.sources.find(s=>s.id===i.region)?.name||i.region;return <li key={i.region}><strong>{name}</strong><span>{stateNames[i.status]||i.status} · {n(i.processed)} verarbeitet</span>{i.message&&<small>{i.message}</small>}{job.stage==='metadata'&&i.status!=='unavailable'&&i.status!=='queued'&&<AdminRunDebug region={i.region} name={name}/>}</li>;})}</ul>{jobRows.length>JOB_ROWS&&<p className="admin-note">{n(jobRows.length-JOB_ROWS)} weitere Gebiete sind nicht aufgeführt. „Anzeigen“ grenzt die Liste auf einen Zustand ein.</p>}</details></section>}
  {aiJob&&<section className="admin-job"><h2>KI-Auftrag</h2><p>{aiJob.count} festgelegte Artikel{aiJob.steps!=null&&` · ${aiJob.steps} fehlende Einzelschritte`} · {aiJob.kinds.map(k=>kindNames[k]).join(', ')} · {aiJob.applied} Ergebnisse übernommen</p><p className="admin-note">{aiJob.status==='prepared'?'Reserviert – der Download allein ist keine erfolgreiche Bearbeitung. Auftrag an deinen KI-Agenten übergeben und Ergebnisse hier einlesen; mehrere Teildateien sind möglich. Solange Artikel fehlen, bleibt dieser Auftrag offen.':aiJob.status==='cancelled'?'Auftrag verworfen. Die Artikel sind wieder verfügbar, stehen aber hinter bisher nicht exportierten Artikeln. Vorhandene Analyseergebnisse bleiben erhalten.':'Ergebnisse übernommen. Fachliche Quellenlücken können weiterhin bestehen.'}</p><div className="admin-selection-actions"><Button variant="outline" disabled={!!busy||running} onClick={()=>action('download-job',async()=>{await downloadAi(aiJob.id);setMessage('Auftrag erneut heruntergeladen. Die Artikelauswahl bleibt unverändert.');})}><Download size={16}/> Auftrag herunterladen</Button>{aiJob.status==='prepared'&&<><Button disabled={busySource} onClick={()=>file.current?.click()}>Ergebnisse prüfen & speichern</Button><Button variant="ghost" disabled={busySource} onClick={()=>action('cancel-ai',async()=>{await api('/api/admin/ai-job',{action:'cancel',id:aiJob.id});await refresh();})}>Auftrag verwerfen</Button></>}<input ref={file} hidden type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importAi(f);e.target.value='';}}/></div><details><summary>Arbeitsauftrag an den KI-Agenten</summary><p>„Lies requirements/ai-processing.md und die heruntergeladene Auftragsdatei. Bearbeite nur die darin ausgewählten Artikel und Schritte. Erzeuge und validiere die Ergebnisdatei gemäß shared/ai-job.mjs.“</p></details></section>}
  <section className="admin-storage-status"><h2>Export und lokale Übernahme</h2>{restore?<p><Check size={17}/> In dieser Datenbank wurde am {date(restore.at)} ein geprüfter Export vom {date(restore.sourceCreatedAt)} übernommen. {restore.localRevision===data.processing.revision?'Seit dieser Übernahme ist die Inhaltsrevision unverändert.':'Seitdem kann der Bestand weiterbearbeitet worden sein; der aktuelle Stand wird oben angezeigt.'}</p>:<p>In dieser Datenbank ist noch kein Übernahmebeleg hinterlegt. Ein Download bestätigt keine Speicherung auf einem anderen PC.</p>}{data.processing.lastAiApply&&<p>Letzter geprüfter KI-Import: {date(data.processing.lastAiApply.at)} · {data.processing.lastAiApply.applied} gespeichert · {data.processing.lastAiApply.conflicts.length} Konflikte.</p>}<p className="admin-note">Wenn du lokal arbeitest, speichern Abruf und Analysen direkt in der lokalen Datenbank; dafür ist kein zusätzlicher Export nötig. Für die Übertragung aus dem Online-System: Export herunterladen, mit dem Wiederherstellungswerkzeug lokal einlesen und diese Seite lokal öffnen.</p></section>
  <DatabaseAdmin sources={data.sources} disabled={busySource}/>
  <AdminTimeline selected={selected} revision={data.processing.revision}/>
  <footer className="admin-footer">Bestandszahlen schließen zusammengeführte Verweise aus. <a href="/admin?seite=2">Weitere Funktionen: Qualität & Betrieb →</a></footer>
 </main></div>;
}
