'use client';
import {useState} from 'react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {LABELS,labelName} from '@/shared/labels.mjs';
import {RegionSelect} from './region-select';
function Choice({name,label,value,items,onChange}:{name:string;label:string;value:string;items:{id:string;name:string}[];onChange:(v:string)=>void}){return <div className="analysis-field"><label id={name+'-label'}>{label}</label><Select name={name} value={value} onValueChange={onChange}><SelectTrigger aria-labelledby={name+'-label'}><SelectValue/></SelectTrigger><SelectContent position="popper" className="analysis-options">{items.map(i=><SelectItem key={i.id} value={i.id}>{i.name}</SelectItem>)}</SelectContent></Select></div>}
export function AnalysisControls({data,example}:{data:any;example?:string}){
 const [region,setRegion]=useState(data.region),[topic,setTopic]=useState(data.topicId||'none'),[label,setLabel]=useState(data.label),[level,setLevel]=useState(data.level),[from,setFrom]=useState(data.from),[to,setTo]=useState(data.to),[question,setQuestion]=useState(example||'');
 const dirty=region!==data.region||topic!==(data.topicId||'none')||label!==data.label||level!==data.level||from!==data.from||to!==data.to;
 return <form action="/analysen#auswertung" className="analysis-controls">
  <div className="analysis-basic"><div className="analysis-field analysis-region"><label htmlFor="analysis-region">Stadt, Gemeinde oder Kreis</label><RegionSelect availability={data.regionAvailability} id="analysis-region" value={region} onChange={v=>{setRegion(v);setTopic('none');if(question==='aehnlichkeit')setQuestion('schwerpunkte')}}/></div><div className="analysis-field"><label htmlFor="analysis-from">Von</label><input required id="analysis-from" name="from" type="date" value={from} onChange={e=>setFrom(e.target.value)} max={to||data.today}/></div><div className="analysis-field"><label htmlFor="analysis-to">Bis</label><input required id="analysis-to" name="to" type="date" value={to} onChange={e=>setTo(e.target.value)} min={from} max={data.today}/></div></div>
  <details className="analysis-advanced" open={!!data.topicId||data.level!=='all'}><summary>Vergleich anpassen <span>{topic==='none'?labelName(label):'Konkretes Vorhaben'} · {level==='city'?'Kommunen':level==='district'?'Kreise':'Alle Ebenen'}</span></summary><div className="analysis-advanced-fields"><Choice name="label" label="Sachgebiet für Zeit- und Ortsvergleich" value={label} onChange={v=>{setLabel(v);setTopic('none');if(question==='aehnlichkeit')setQuestion('entwicklung')}} items={LABELS}/><Choice name="level" label="Gebiete auf der Karte" value={level} onChange={setLevel} items={[{id:'all',name:'Kommunen und Kreise'},{id:'city',name:'Nur Städte und Gemeinden'},{id:'district',name:'Nur Kreise'}]}/><div className="analysis-focus"><Choice name="focus" label="Optional: konkretes Vorhaben vergleichen" value={topic} onChange={v=>{setTopic(v);setQuestion(v==='none'?'orte':'aehnlichkeit')}} items={[{id:'none',name:'Gesamtes Sachgebiet vergleichen'},...(region===data.region?data.topicOptions.map((t:any)=>({id:t.id,name:t.title})):[])]}/></div><p className="page-note">Verteilung und Themenmix zeigen immer alle Vorgänge. {topic==='none'?'Die Zeitlinie sowie die Kartenansichten Anteil, Anzahl und Veränderung verwenden das gewählte Sachgebiet.':'Die Kartenansichten Anteil, Anzahl und Veränderung suchen ähnliche Vorhaben zum gewählten Artikel; die Zeitlinie verwendet weiterhin das Sachgebiet.'}{region!==data.region?' Für die Artikelauswahl zuerst den neuen Ort übernehmen.':''}</p></div></details>
  <input type="hidden" name="example" value={question}/><input type="hidden" name="topic" value={topic==='none'?'':topic}/><div className="analysis-submit"><Button className="analysis-apply" type="submit">Auswertung aktualisieren</Button><p role="status">{dirty?'Auswahl geändert – bitte aktualisieren.':'Die angezeigten Ergebnisse entsprechen dieser Auswahl.'}</p></div>
 </form>;
}
