import {buildAnalysisExamples,concreteTopicExamples,labelShortcuts} from '@/shared/analysis-examples.mjs';
export function AnalysisExamples({data,active}:{data:any;active:string}){
 const examples=buildAnalysisExamples(data),selected=examples.find(e=>e.id===active)||examples[0];
 const concrete=concreteTopicExamples(data),shortcuts=labelShortcuts(data,selected.id);
 return <section id="analysebeispiele" className="analysis-examples" aria-labelledby="examples-title">
  <div className="examples-heading"><h2 id="examples-title">Mit einer Frage starten</h2><p>Beispiele für deinen Ort und Zeitraum. Die Auswahl setzt passende Filter und bleibt anpassbar.</p></div>
  <nav className="example-links" aria-label="Analysebeispiele">{examples.map(e=>e.href?<a key={e.id} href={e.href} aria-current={selected.id===e.id?'true':undefined}><span className="example-number">{e.number}</span><span>{e.title}</span></a>:<span key={e.id} className="example-unavailable"><span className="example-number">{e.number}</span><span>{e.title}<small>Kein passender Artikel im Zeitraum</small></span></span>)}</nav>
  <div className="example-result"><div className="example-result-title"><p className="eyebrow">{selected.title}</p><h3>{selected.metric}</h3></div><div><p className="example-answer">{selected.answer}</p><p className="page-note">{selected.note}</p><a className="example-detail" href={'#'+selected.target}>{selected.action} ↓</a>{selected.id==='entwicklung'&&<a className="example-detail mix-jump" href="#themenmix">Alle Sachgebiete im Monatsvergleich ↓</a>}</div></div>
  {['entwicklung','orte'].includes(selected.id)&&shortcuts.length>0&&<nav className="example-subjects" aria-label="Sachgebiet für dieses Beispiel wählen"><p>Dieses Beispiel mit einem anderen Sachgebiet:</p><div>{shortcuts.map((l:{id:string;name:string;count:number;href:string})=><a key={l.id} href={l.href} aria-current={l.id===data.label&&!data.focus?'true':undefined}>{l.name}<span>{l.count}</span></a>)}</div></nav>}
  {selected.id==='aehnlichkeit'&&<p className="page-note">{selected.description}</p>}
  <details className="concrete-examples" open={selected.id==='aehnlichkeit'}><summary>Konkrete Themen ausprobieren <span>{concrete.length} Sachthemen in deiner Auswahl</span></summary><p className="page-note">Aus Vorgängen deines Orts im gewählten Zeitraum. Ein Beispiel öffnen, um ähnliche Vorhaben in anderen Orten zu suchen.</p>
   {concrete.length?<><div className="concrete-grid">{concrete.slice(0,6).map(e=><a key={e.subject} href={e.href} aria-current={selected.id==='aehnlichkeit'&&e.active?'true':undefined}><div className="concrete-card-heading"><strong>{e.subject}</strong><span>{e.count} {e.count===1?'Vorgang':'Vorgänge'} vor Ort</span></div><p>{e.chosen.title}</p><span className="concrete-action">Dieses Vorhaben vergleichen</span></a>)}</div>{concrete.length>6&&<details className="more-concrete"><summary>Weitere {concrete.length-6} Sachthemen</summary><ul>{concrete.slice(6).map(e=><li key={e.subject}><a href={e.href}>{e.subject} · {e.count} {e.count===1?'Vorgang':'Vorgänge'} vor Ort</a></li>)}</ul></details>}<p className="page-note">Gezählt werden Titel mit dem jeweiligen Sachthema. Ein Vorgang kann mehrere Sachthemen enthalten. Die Zahlen sind keine Anzahl gefundener Ähnlichkeiten.</p></>:<p className="empty-state">Für diese Auswahl gibt es noch kein geeignetes konkretes Beispiel. Du kannst oben einen anderen Ort oder Zeitraum wählen.</p>}
  </details>
 </section>;
}
