import type {TopicDetail} from '@/shared/types';
import {formatDate} from '@/shared/types';
import {labelName} from '@/shared/labels.mjs';
export function ArticleAnalysis({topic:t}:{topic:TopicDetail}){
 const a=t.contentAnalysis;
 return <>
  {a&&<section className="prose analysis-provenance" aria-labelledby="analysegrundlage"><h2 id="analysegrundlage" className="heading-m">Grundlage der Zusammenfassung</h2><p><strong>{a.status==='completed'?'KI-Inhaltszusammenfassung':a.status==='stale'?'Aktualisierung ausstehend':'Quellenlage unzureichend'}</strong> · Bearbeitet {formatDate(a.generatedAt)}</p><p>{a.basis}</p>{a.reason&&<p className="page-note">{a.reason}</p>}<p className="page-note">{a.reviewStatus==='reviewed'?'Unabhängig geprüft.':'KI-generiert und technisch geprüft; noch nicht unabhängig fachlich geprüft.'}</p>{a.evidence.length>0&&<details><summary>Belegstellen in den Originalquellen</summary><ul>{a.evidence.map((e,i)=><li key={i}><q>{e.quote}</q> <a href={e.url} target="_blank" rel="noopener noreferrer">{e.location||'Originalquelle'}</a></li>)}</ul></details>}</section>}
  {t.weightedKeywords&&<section className="prose"><h2 className="heading-m">Gewichtete Suchbegriffe</h2><p className="page-note">{t.weightedKeywords.status==='stale'&&<strong>Veraltet: Originaltitel wurde geändert. </strong>}{t.weightedKeywords.basis} Die Gewichte ergeben zusammen 100 und beschreiben die relative Bedeutung innerhalb dieses Artikels.</p><ul className="keyword-list">{t.weightedKeywords.items.map(k=><li key={k.term}><span>{k.term}</span><strong>{k.weight}</strong></li>)}</ul></section>}
  {t.labelAssessments&&<section className="prose"><h2 className="heading-m">Regeln und KI im Vergleich</h2><dl className="facts"><div className="facts__row"><dt>Regelbasiert</dt><dd>{t.labelAssessments.rule?labelName(t.labelAssessments.rule.primary):'Ausstehend'}</dd></div><div className="facts__row"><dt>KI-Bewertung</dt><dd>{t.labelAssessments.ai?labelName(t.labelAssessments.ai.primary)+(t.labelAssessments.ai.status==='stale'?' · veraltet':''):'Ausstehend'}</dd></div><div className="facts__row"><dt>Unabhängige Referenz</dt><dd>{t.labelAssessments.review?labelName(t.labelAssessments.review.primary):'Noch nicht bewertet'}</dd></div></dl>{t.labelAssessments.ai&&<p className="page-note">{t.labelAssessments.ai.reason}</p>}</section>}
  {t.metadata&&<section className="prose"><details><summary>Bearbeitungszeitpunkte</summary><dl className="facts">{([['Amtlich geändert',t.metadata.sourceModifiedAt],['Erstmals importiert',t.metadata.firstImportedAt],['Zuletzt abgerufen',t.metadata.lastFetchedAt],['Intern verarbeitet',t.metadata.lastProcessedAt]] as const).map(([label,value])=><div key={label} className="facts__row"><dt>{label}</dt><dd>{value?formatDate(value):'Nicht dokumentiert'}</dd></div>)}</dl></details></section>}
 </>;
}
export function SessionDetails({event:e}:{event:TopicDetail['events'][number]}){return <>
 {e.decision&&<div className="session-details"><p><strong>{e.decision.kind==='recommendation'?'Empfehlung':e.decision.kind==='decision'?'Beschlussergebnis':'Dokumentiertes Ergebnis'}</strong>: {e.decision.text}</p>{e.decision.votes&&<p>Abstimmung: {e.decision.votes.description||[e.decision.votes.yes!==null?e.decision.votes.yes+' Ja':null,e.decision.votes.no!==null?e.decision.votes.no+' Nein':null,e.decision.votes.abstentions!==null?e.decision.votes.abstentions+' Enthaltungen':null].filter(Boolean).join(', ')||'Keine Zahlen veröffentlicht'}</p>}<p className="page-note">Umsetzung: {e.decision.implementationStatus==='reported_complete'?'als abgeschlossen dokumentiert':'nicht belegt'}</p><a className="text-link" href={e.decision.sourceUrl} target="_blank" rel="noopener noreferrer">Ergebnis im Original</a></div>}
 {e.attendance&&<details className="session-details"><summary>Teilnahme an der Sitzung{e.attendance.status==='available'?' ('+e.attendance.people.length+' dokumentierte Personen)':''}</summary>{e.attendance.status==='available'?<><p className="page-note">Anwesenheit in der Sitzung; keine Aussage über die Teilnahme an jedem einzelnen Tagesordnungspunkt.</p><ul>{e.attendance.people.map((p,i)=><li key={i}>{p.name} · {p.role} · {p.presence==='present'?'anwesend':p.presence==='absent'?'abwesend':'Anwesenheit offen'}</li>)}</ul></>:<p>Keine auswertbare Anwesenheitsliste erfasst.</p>}{e.attendance.sourceUrl&&<a className="text-link" href={e.attendance.sourceUrl} target="_blank" rel="noopener noreferrer">Amtliche Anwesenheitsliste</a>}</details>}
 </>}
