import {LABELS} from '@/shared/labels.mjs';
import {analysisHref} from '@/shared/analysis-examples.mjs';
import {formatDate} from '@/shared/types';
const pct=(n:number|null)=>n===null?'—':n.toLocaleString('de-DE',{maximumFractionDigits:1})+' %';
const delta=(n:number)=>(n>0?'+':'')+n.toLocaleString('de-DE',{maximumFractionDigits:1})+' Pp.';
const month=(s:string)=>s.slice(5)+'.'+s.slice(0,4);
export function MonthlyMix({data}:{data:any}){
 const comparison=data.monthlyComparison,activeLabels=LABELS.filter(l=>data.months.some((m:any)=>m.distribution.some((v:any)=>v.id===l.id&&v.count>0)));
 const labelLink=(id:string)=>analysisHref(data,'entwicklung',{label:id}).replace('#analysebeispiele','#themenmix');
 return <section id="themenmix" className="analysis-panel monthly-mix" aria-labelledby="mix-title"><div className="mix-heading"><div><p className="eyebrow">MONATE VERGLEICHEN</p><h2 id="mix-title">Wie verändert sich der Themenmix?</h2></div><p className="page-note">Ein Balken entspricht 100 % der Vorgänge eines Monats. Allgemeine, formale und offene Einordnungen sind enthalten.</p></div>
  {activeLabels.length?<><div className="mix-bars" role="img" aria-label="Themenanteile je Monat als gestapelte Balken. Genaue Werte stehen in der aufklappbaren Monatstabelle.">{data.months.map((m:any)=><div key={m.month} className="mix-month"><div className="mix-month-name"><strong>{month(m.month)}</strong><span>{m.total?`${m.total} Vorgänge`:'Keine Daten'}</span></div>{m.total?<div className="mix-stack">{m.distribution.filter((l:any)=>l.count>0).map((l:any)=><span key={l.id} className={data.label===l.id?'mix-segment selected':'mix-segment'} style={{width:l.share+'%',background:l.color}} title={`${l.name}: ${l.count} von ${m.total} (${pct(l.share)})`}/>)}</div>:<div className="mix-gap">Kein auswertbarer Monatsbestand</div>}<span className="mix-month-state">{m.total?(m.partial?'Teilstand':'Erfasster Bestand'):'Lücke'}</span></div>)}</div><nav className="mix-legend" aria-label="Sachgebiet im Monatsvergleich hervorheben">{activeLabels.map(l=><a key={l.id} href={labelLink(l.id)} aria-current={data.label===l.id?'true':undefined}><i aria-hidden="true" style={{background:l.color}}/>{l.name}</a>)}</nav></>:<p className="empty-state">Für den gewählten Zeitraum liegen keine datierten Vorgänge vor.</p>}
  <div className="mix-changes"><h3>Größte Veränderungen bei den Sachgebieten</h3>{comparison.available?<><p className="page-note">Verglichen werden {formatDate(comparison.first.from)}–{formatDate(comparison.first.to)} ({comparison.first.total} Vorgänge) und {formatDate(comparison.last.from)}–{formatDate(comparison.last.to)} ({comparison.last.total} Vorgänge). {comparison.gaps>0?`${comparison.gaps} Monate dazwischen ohne Daten.`:''}</p>{comparison.changes.length?<div className="table-scroll" tabIndex={0} role="region" aria-label="Monatsänderungen, bei Bedarf seitlich scrollen"><table className="analysis-table"><caption className="sr-only">Die bis zu fünf größten absoluten Änderungen fachlicher Anteile. Pp. bedeutet Prozentpunkte.</caption><thead><tr><th>Sachgebiet</th><th>{month(comparison.first.month)}</th><th>{month(comparison.last.month)}</th><th>Änderung</th></tr></thead><tbody>{comparison.changes.slice(0,5).map((l:any)=><tr key={l.id}><th><a href={labelLink(l.id)}>{l.name}</a></th><td>{l.firstCount} / {comparison.first.total}<small>{pct(l.firstShare)}</small></td><td>{l.lastCount} / {comparison.last.total}<small>{pct(l.lastShare)}</small></td><td className="mix-delta">{delta(l.delta)}</td></tr>)}</tbody></table></div>:<p>Die fachlichen Anteile sind in beiden Monaten gleich.</p>}<p className="page-note">Pp. = Prozentpunkte. Ausgewertet werden erster und letzter Monat mit Daten. Die Änderung beschreibt den erfassten Bestand; Teilmonate, Quellenlücken und kleine Fallzahlen können sie beeinflussen. Ein höherer Anteil kann auch durch weniger Vorgänge anderer Sachgebiete entstehen. Daraus lässt sich kein gesicherter politischer Trend ableiten.</p></>:<p className="page-note">Für einen Vergleich sind mindestens zwei Monate mit erfassten Vorgängen erforderlich.</p>}</div>
  {activeLabels.length>0&&<details className="analysis-details"><summary>Alle Monatswerte als Tabelle</summary><div className="table-scroll" tabIndex={0} role="region" aria-label="Monatswerte aller Themenlabels"><table className="analysis-table mix-values"><caption>Anzahl und Anteil je Monat, einschließlich allgemeiner und offener Einordnungen</caption><thead><tr><th>Themenlabel</th>{data.months.map((m:any)=><th key={m.month}>{month(m.month)}<small>{m.total?`${m.total} Vorgänge${m.partial?' · Teilstand':''}`:'Keine Daten'}</small></th>)}</tr></thead><tbody>{LABELS.map(l=><tr key={l.id}><th>{l.name}</th>{data.months.map((m:any)=>{const v=m.distribution.find((v:any)=>v.id===l.id);return <td key={m.month}>{m.total?`${v.count} · ${pct(v.share)}`:'—'}</td>})}</tr>)}</tbody></table></div></details>}
 </section>;
}
