'use client';
import {useEffect,useState} from 'react';



import {Switch} from '@/components/ui/switch';
export function Notifications(){const[busy,setBusy]=useState(false);const[active,setActive]=useState(false);const[message,setMessage]=useState('');const[key,setKey]=useState('');const[supported,setSupported]=useState(false);useEffect(()=>{const ok='serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window;setSupported(ok);if(ok){navigator.serviceWorker.register('/sw.js').then(r=>r.pushManager.getSubscription()).then(s=>setActive(!!s)).catch(()=>setSupported(false));fetch('/api/push/config').then(r=>r.json()).then((x:unknown)=>setKey((x as {publicKey?:string}).publicKey||'')).catch(()=>{});}},[]);
async function change(next:boolean){setBusy(true);setMessage('');try{const registration=await navigator.serviceWorker.ready;if(!next){const sub=await registration.pushManager.getSubscription();if(sub){const r=await fetch('/api/push/subscribe',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({endpoint:sub.endpoint})});if(!r.ok)throw Error('Das Ausschalten hat nicht geklappt. Bitte versuche es erneut.');await sub.unsubscribe()}setActive(false);setMessage('Benachrichtigungen sind ausgeschaltet.');return}const permission=await Notification.requestPermission();if(permission!=='granted'){setMessage('Benachrichtigungen wurden nicht erlaubt. Du kannst die Berechtigung in deinen Browser-Einstellungen ändern.');return}const sub=await registration.pushManager.getSubscription()||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:Uint8Array.from(atob(key.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0))});const r=await fetch('/api/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(sub.toJSON())});if(!r.ok){await sub.unsubscribe();throw Error('Die Anmeldung konnte nicht gespeichert werden. Bitte versuche es später noch einmal.')}setActive(true);setMessage('Du erhältst künftig Hinweise auf neu erkannte Beschlüsse.')}catch(e){setMessage(e instanceof Error?e.message:'Das hat leider nicht geklappt.')}finally{setBusy(false)}}
return <section className="notification-panel" aria-labelledby="push"><h2 id="push" className="section-title">Push-Nachrichten</h2><div className="setting"><label className="setting__label" htmlFor="push-enabled"><span className="setting__name">Neue Beschlüsse</span><span className="setting__hint">Entscheidungen von Rat, Ausschüssen und Bezirksvertretungen</span></label><Switch id="push-enabled" checked={active} disabled={busy||!supported||!key} onCheckedChange={change}/></div>{!supported?<p className="notice">Dieser Browser unterstützt hier keine Push-Nachrichten. Auf dem iPhone kannst du die Website zum Home-Bildschirm hinzufügen und dort öffnen.</p>:!key?<p className="notice">Benachrichtigungen sind noch nicht verfügbar. Bitte versuche es später erneut.</p>:<p className="page-note">Deine Auswahl gilt für dieses Gerät. Der Versand setzt neu eingelesene Entscheidungen voraus.</p>}{message&&<p role="status" className="notice">{message}</p>}</section>}
