'use client';
import {useState} from 'react';
import {Check,ChevronsUpDown} from 'lucide-react';
import {Popover,PopoverContent,PopoverTrigger} from '@/components/ui/popover';
import {Command,CommandInput,CommandList,CommandEmpty,CommandItem} from '@/components/ui/command';
import {availabilityLabel} from '@/shared/region-availability.mjs';
import {REGIONS,regionName,type Region} from '@/shared/regions';
export type RegionAvailability=Record<string,{count:number;partial:boolean}>;
export function RegionSelect({availability,value,onChange,name='region',id,options=REGIONS,label='Stadt, Gemeinde oder Kreis auswählen'}:{availability:RegionAvailability;value:string;onChange:(v:string)=>void;name?:string;id?:string;options?:Region[];label?:string}){const [open,setOpen]=useState(false);return <><input type="hidden" name={name} value={value}/><Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><button id={id} type="button" className="region-search-trigger" aria-expanded={open} aria-haspopup="dialog" aria-label={label+': '+regionName(value)+', '+availabilityLabel(availability[value])}><span>{regionName(value)}<small className="region-trigger-count">{availabilityLabel(availability[value])}</small></span><ChevronsUpDown size={18}/></button></PopoverTrigger><PopoverContent className="region-search-popover" align="start"><p className="region-data-hint">Artikel im Gesamtbestand. Teilstand bedeutet: bekannte Datenlücken.</p><Command><CommandInput aria-label="Gebiete durchsuchen" placeholder="Name oder Gemeindeschlüssel …"/><CommandList><CommandEmpty>Kein Gebiet gefunden.</CommandEmpty>{options.map(r=><CommandItem key={r.id} value={r.name+' '+r.ags} onSelect={()=>{onChange(r.id);setOpen(false)}}><Check size={16} style={{opacity:value===r.id?1:0}}/><span className="region-option-text">{r.name}<small>{r.kind==='district'?'Kreis / Städteregion':r.district?regionName(r.district):'Kreisfreie Stadt'} · {r.ags}</small><span className={'region-data-badge'+(availability[r.id]?.count?' has-data':' no-data')}>{availabilityLabel(availability[r.id])}</span></span></CommandItem>)}</CommandList></Command></PopoverContent></Popover></>}
