// Wortliste der Titelregeln je Sachgebiet (shared/labels.mjs baut daraus die Suchmuster; Lena nutzt die Begriffe als
// Themen-Synonyme). Reihenfolge der Sachgebiete ist die Prüfreihenfolge. Einträge sind Teilmuster eines regulären Ausdrucks
// (ohne Groß-/Kleinschreibung): meist ein Wortanfang, teils mit \\b oder Ausschlüssen. Nach Änderungen messen:
// node scripts/label-study/measure-rules.mjs --set=label-holdout-6 --fehler
/** @type {Record<string,string[]>} */
export const LABEL_WORDS={
 bildung:["\\bkiga\\b","\\bggs\\b","\\bkgs\\b","kindertages","kindergarten","kinderbetreuung","kita\\b","elternbeitr","schul","ganztag","\\bogs\\b","weiterbildung","volkshochschule","betreuungsplatz","erasmus","klassenfahrt","tagesausflüge","jugend und bildung","berufskolleg","schulleitung","kinderzahlen","anmeldeverhalten","\\bbne\\b","bildung für nachhaltige","schließtage","ganztägig","politischen? bildung"],
 bauen:["bebauungsplan","flächennutzungsplan","bauleitplan","baugebiet","\\bwohnen\\b","wohnhaus","wohneinheit","grundstück","flurstück","erschließung","erschliessung","baubeschluss","bauvorhaben","wohnraum","wohnung(?!slos|ssteuer)","wohnbau","bauland","städtebau","stadtentwickl","stadtteilentwickl","leerstand","bauantrag","baugenehmigung","denkmalschutz","sanierungsgebiet","leerständ","entwicklungskonzept","erschließungsanlage","quartiersentwicklung","zweckentfremdung","denkmalbehörde","offenlage","bauleitplän","bauleitplanung","bauvoranfrage","bauantr","bau-?turbo","regionalplan","planungsraum","außenbereichssatzung","tragwerksplanung","umnutzung","abbruch","renovierung","\\bbaugb\\b","tiefbau","fensterarbeiten","dorfgemeinschaftshaus","stadtplatz","neugestaltung","wiederaufbau","aufstockung","vorkaufsrecht"],
 mobilitaet:["fußweg","fussweg","zebrastreifen","wirtschaftsweg","haltestell","bushalte","rad.?vorrang","buspark","parkausweis","parksituation","parkplatz","tempomess","tempo.?30","e.scooter","poller","pöller","p&r","straßenbeleuchtung","ampel","\\bkvb\\b","\\bnwl\\b","brücken","brücke","radverbindung","veloroute","fahrrad","gehweg","bürgersteig","halteverbot","geschwindigkeits","verkehrsberuhigung","unfallkommission","nahverkehr","öpnv","busverkehr","regionalbus","radverkehr","radweg","radschnell","straßen","strasse","verkehr","parken","parkraum","deutschlandticket","bahnverkehr","stellplatz","ladeinfrastruktur","e-mobilität","mobilität","liniennetz","verkehrssicherheit","verkehrskonzept","widmungsverfahren","stadtbahn","kreuzung","umgehung","s-bahn","straßenendausbau","straßenbauprogramm","straßenbau","grunderneuerung","beleuchtung","fahrradstraße","gleiserneuerung","mobilstation","bahnhof","\\bbhf\\b","personenunterführung","bürgerbus","zusatzfahrten","fahrspur","endausbau","erneuerung der [^.;]{0,40}straße","umgestaltung [^.;]{0,30}straße","\\blinie \\d","kreisstraße","kreisverkehr","fahrbahn","parkplätz","parkleitsystem","parkgebühr","bewohnerpark","bahnübergang","abbiege","wegebau","wegebereisung","ticketautomat","\\bspnv\\b","winterdienst","querung","straßensperr","parkfläch","bordstein","zustand des .{0,25}weg"],
 umwelt:["grüngürtel","wegränder","laubabf","begrünung","grünordnung","nachhaltigkeitsbericht","\\bbaum\\b","recycling","lärmschutz","lärmbelastung","bäume","naturschutz","landschaftsplan","biodiversität","gewässer","abwasser","abfall","abfälle","abfällen","müll","grünfläche","baumfäll","baumschutz","artenschutz","trinkwasser","wasserwirtschaft","kläranlage","altkleider","landschaftsschutz","bnatschg","\\branger\\b","forstwirtschaft","\\bigel","grünschnitt","elektroschrott","sperrmüll","ersatzgeld","entsiegel","depflaster","schottergärt","entwässerung","hochwasser","moorboden","\\bheide\\b","vorgärten","wiederherstellung der natur","wasserkonzept","wasserwerk","wasserbezug","wasserversorg","durchlass","tauschhaus","pflanzung","baumpflege","papiercontainer","glascontainer","altglas","wurzel","kreuzkraut","neophyt","baumpflanz","wasserhaus","wasserampel","regenrückhalte","\\bteich","rheinufer","grünpflege","waldwirtschaft","\\bwald\\b","forst"],
 klima:["energetisch","klimaschutz","klimaanpass","wärmeplan","energie","photovoltaik","windkraft","windpark","solaranlage","hitzeschutz","starkregen","stromnetz","bürgerwind","windenergie","windrad","solar","kraftwerk","batteriespeicher","wärmeleitung","hitzestress","windenergiegebiet","konzessionsvertr","gaskonzession","stromkonzession","klimabeirat","klimaanalyse","stadtklima","pv-?park","pv-anlage","\\bpv\\b"],
 soziales:["geflüchtet","barrierefrei","mobile.{0,8}rampen","lsbti","antidiskriminier","lebenslagenbericht","istanbul.konvention","intergeschlecht","lesben","schwule","diversity","inklusiv","kinder[- ]+und[- ]+jugendparlament","sozial(?!raum|räume)","integration","inklusion","jugendhilfe","jugendamt","jugendförder","asyl","flüchtling","obdachlos","wohnungslos","gleichstellung","behinderten","senioren","jobcenter","\\bkdu\\b","kosten der unterkunft","bedarfe für unterkunft","frauenhaus","\\bcsd\\b","christopher street","gehörlos","eingliederungshilfe","demokratieförder","sozialleistung","bezahlkarte","interkulturell","verbraucherzentrale","generationen","teilhabe","armut","jugendrat","seniorenvertretung","\\bfrauen\\b","diversität","kinderrechte","jugendbeirat","seniorenheim","betreutes wohnen","betreuten wohnens","sexuell","missbrauch","kinderschutz","stadtteilkoordinat","gender","jugendschutz","verfahrenslotse","sgb viii","personalkostenzuschuss","ehrenamt(?!lich)","kinderbeauftragt","inklusionsbeauftragt","menschen mit behinderung"],
 gesundheit:["stillfreundlich","stillmöglichkeiten","arztpraxis","ärzte","gesundheit","\\bpflege\\b","pflegeheim","pflegebedürft","krankenhaus","medizin","suchtprävention","hospiz","sucht(?:beratung|hilfe)","ersthelfer","herz-kreislauf","healthy","außerklinisch","gemeindeschwester","defibrillator","notarzt","lebensmittelüberwachung"],
 wirtschaft:["gewerbe","wirtschaftsförder","wirtschaftsentwick","arbeitsmarkt","beschäftigung","tourismus","einzelhandel","standortförder","gründer","\\bleader\\b","wirtschaftsfläch","wohnmobil","stadtmarketing"],
 kultur:["künste","darstellende kunst","kultur","museum","bibliothek","bücherei","theater","musikschule","konzert","stadtarchiv","kunstverein","ausstellung","archivgut","chor\\b","kreativ","städtepartnerschaft","partnerstadt","jubiläum","kunst(?!stoff|rasen)","stipendium","heimatpflege","stolperstein","dorffest","seefest","\\bfest\\b","ehrenmal","weihnachts","martinsfeuer","gospel","(?<!jugend)veranstaltung","chronik","erinnern"],
 sport:["boulebahn","badefahrten","\\bsport","wassersport","zweifachhalle","dreifachhalle","turnhalle","jugendzentrum","familienferienprogramm","freizeit","schwimmbad","hallenbad","freibad","spielplatz","bäder","jugendtreff","wanderweg","padel","tennis","skatepark","sportanlage","sportplatz","volleyball","fußball","turnverein","kleinspielfeld","spielfeld","sportstätte","spielplätze","\\w+vereins?\\b","zeltlager","\\bzelte\\b","boule","boßeln","skateanlage","outdoorplatz","idraet","meisterschaft","badesaison","\\bdlrg\\b","wandern","aktivroute","sportsstätte","badeordnung","trailpark","trainingspark","jugendveranstaltung"],
 sicherheit:["böller","sicherheitskonzept","\\bfriedhof\\b","friedhofsverwaltung","grablicht","feuerwehr","brandschutz","katastrophenschutz","bevölkerungsschutz","rettungsdienst","rettungswache","\\bordnungs(?!gemäß|mäßig|-)","polizei","gefahrenabwehr","kriminal","friedhofseinrichtung","friedhofsordnung","friedhofssatzung","einsatzfahrzeug","betteln","verunreinigung","vermüllung","\\bratten","gefahrenlage","wehrführer","abgemeldete fahrzeuge","schrottfahrzeug","alarm- und einsatz","einsatzpl","bestattung","friedhofs-","entwidmung.{0,20}friedhof"],
 finanzen:["\\bfinanzen\\b","sachinvestitionsmittel","infrastrukturgesetz","beteiligungen.{0,45}unternehmen","schenkung","haushalt","jahresabschluss","gesamtabschluss","steuer","verschuldung","kreditaufnahme","finanzbericht","finanzplanung","finanzcontrolling","kassenprüfung","stundung","niederschlagung","geldforderung","stellenplan","zwischenbericht","kassenwart","sondervermögen","\\betat\\b","budget","investitionsplan","ergebnisplan","bilanzierungshilfe","\\bnkf\\b","jahresabschlussprüfung","wirtschaftsplan","sponsoring","spenden","finanzmittel","kreisumlage","jahresrechnung","außerplanmäßig","überplanmäßig","investitionsmittel","drittmittel","(?:\\bag|gmbh|\\bkg)\\b[: ].{0,30}satzungsänderung","geldzuwendung","darlehen","verfügbare mittel","bilanz","controlling","ergebnisrechnung","gebührensatzung","investitionsprogramm","abschlussprüfer","einsparvorschl"],
 verwaltung:["verwaltungs","digitalisier","bürgerservice","personal","stellenplan","ratsarbeit","geschäftsordnung","gremienbesetzung","umbesetzung","wahlen","wahlordnung","hauptsatzung","datenschutz","informationssicherheit","organisationsstruktur","organigramm","nebentätigkeit","kennzahl","smart.?city","öffentlich-rechtlichen? vereinbarung","gebäudemanagement","servicezeiten","bürgerbüro","gesellschaftsvertr","beteiligungsunternehmen","betriebssatzung","organisationsuntersuchung","bezahldienst","digitale souveränität","\\bserver","schließsystem","liegenschaft","benutzungsordnung","\\bagbs?\\b","personenbezogen","auskunftssperr","bürgerentscheid","kommunalwahl","raupenbagger","bauhof","stadtlogo","\\blogo\\b","corporate design","standesbeamt","öffentlichkeitsarbeit","whatsapp","mobilfunk","digitaler form","gebäudereinigung","glasreinigung","betriebszentrum","sitzungsunterlagen"],
};
/** Begriffe, die sich als Klartext lesen lassen (ohne Sonderzeichen), für Vorschläge und Synonyme. */
export const plainWords=id=>(LABEL_WORDS[id]||[]).map(p=>p.replace(/\\b/g,'')).filter(p=>/^[a-zäöüß][a-zäöüß .-]*$/i.test(p)&&p.length>=4);
export const LABEL_WORD_IDS=Object.keys(LABEL_WORDS);
